// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.3,
// any modifications will be overwritten.
// ==============================================================

package com.webix.ui.model.context;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import com.webix.ui.model.AnimateConfig;
import com.webix.ui.model.Baselayout;
import com.webix.ui.model.Baseview;
import com.webix.ui.model.DelimiterConfig;
import com.webix.ui.model.EventHandler;
import com.webix.ui.model.EventHandlerList;
import com.webix.ui.model.GraphItemConfig;
import com.webix.ui.model.NavigationConfig;
import com.webix.ui.model.PaddingConfig;
import com.webix.ui.model.Proto;
import com.webix.ui.model.RGBColorList;
import com.webix.ui.model.TypeConfig;
import com.webix.ui.model.UnknownType;
import com.webix.ui.model.View;
import com.webix.ui.model.auxiliary.Calendar;
import com.webix.ui.model.auxiliary.Colorboard;
import com.webix.ui.model.auxiliary.Pager;
import com.webix.ui.model.auxiliary.Resizer;
import com.webix.ui.model.auxiliary.Spacer;
import com.webix.ui.model.auxiliary.Tooltip;
import com.webix.ui.model.auxiliary.Video;
import com.webix.ui.model.data.Chart;
import com.webix.ui.model.data.Datatable;
import com.webix.ui.model.data.Dataview;
import com.webix.ui.model.data.Grouplist;
import com.webix.ui.model.data.List;
import com.webix.ui.model.data.Property;
import com.webix.ui.model.data.Tree;
import com.webix.ui.model.data.Treetable;
import com.webix.ui.model.data.Unitlist;
import com.webix.ui.model.form.Button;
import com.webix.ui.model.form.Checkbox;
import com.webix.ui.model.form.Colorpicker;
import com.webix.ui.model.form.Combo;
import com.webix.ui.model.form.Counter;
import com.webix.ui.model.form.Datepicker;
import com.webix.ui.model.form.Fieldset;
import com.webix.ui.model.form.Icon;
import com.webix.ui.model.form.Label;
import com.webix.ui.model.form.Multiselect;
import com.webix.ui.model.form.Multitext;
import com.webix.ui.model.form.Radio;
import com.webix.ui.model.form.Richselect;
import com.webix.ui.model.form.Search;
import com.webix.ui.model.form.Segmented;
import com.webix.ui.model.form.Select;
import com.webix.ui.model.form.Slider;
import com.webix.ui.model.form.Tabbar;
import com.webix.ui.model.form.Text;
import com.webix.ui.model.form.Textarea;
import com.webix.ui.model.form.Toggle;
import com.webix.ui.model.html.Htmlform;
import com.webix.ui.model.html.Iframe;
import com.webix.ui.model.html.Scrollview;
import com.webix.ui.model.html.Template;
import com.webix.ui.model.layouts.Accordion;
import com.webix.ui.model.layouts.Accordionitem;
import com.webix.ui.model.layouts.Carousel;
import com.webix.ui.model.layouts.Form;
import com.webix.ui.model.layouts.Headerlayout;
import com.webix.ui.model.layouts.Layout;
import com.webix.ui.model.layouts.Multiview;
import com.webix.ui.model.layouts.Tabview;
import com.webix.ui.model.layouts.Toolbar;





/**
 * A context menu.The component presents a pop-up menu that is
 * displayed when the user clicks the right mouse button in the
 * client area. You can configure any nesting level complexity.
 * Check <a
 * href="http://docs.webix.com/desktop__contextmenu.html">contextmenu</a>
 * documentation for more detailed description.
 * 
 * @version $Revision$ $Date$
 */
@com.webix.ui.model.WebixEvent({
    com.webix.ui.model.Event.ON_AFTER_ADD,
    com.webix.ui.model.Event.ON_AFTER_CONTEXT_MENU,
    com.webix.ui.model.Event.ON_AFTER_DELETE,
    com.webix.ui.model.Event.ON_AFTER_DROP,
    com.webix.ui.model.Event.ON_AFTER_LOAD,
    com.webix.ui.model.Event.ON_AFTER_RENDER,
    com.webix.ui.model.Event.ON_AFTER_SCROLL,
    com.webix.ui.model.Event.ON_AFTER_SELECT,
    com.webix.ui.model.Event.ON_AFTER_SORT,
    com.webix.ui.model.Event.ON_BEFORE_ADD,
    com.webix.ui.model.Event.ON_BEFORE_CONTEXT_MENU,
    com.webix.ui.model.Event.ON_BEFORE_DELETE,
    com.webix.ui.model.Event.ON_BEFORE_DRAG,
    com.webix.ui.model.Event.ON_BEFORE_DRAG_IN,
    com.webix.ui.model.Event.ON_BEFORE_DROP,
    com.webix.ui.model.Event.ON_BEFORE_DROP_OUT,
    com.webix.ui.model.Event.ON_BEFORE_LOAD,
    com.webix.ui.model.Event.ON_BEFORE_RENDER,
    com.webix.ui.model.Event.ON_BEFORE_SELECT,
    com.webix.ui.model.Event.ON_BEFORE_SHOW,
    com.webix.ui.model.Event.ON_BEFORE_SORT,
    com.webix.ui.model.Event.ON_BIND_REQUEST,
    com.webix.ui.model.Event.ON_DATA_REQUEST,
    com.webix.ui.model.Event.ON_DATA_UPDATE,
    com.webix.ui.model.Event.ON_DESTRUCT,
    com.webix.ui.model.Event.ON_DRAG_OUT,
    com.webix.ui.model.Event.ON_HIDE,
    com.webix.ui.model.Event.ON_ITEM_CLICK,
    com.webix.ui.model.Event.ON_ITEM_DBL_CLICK,
    com.webix.ui.model.Event.ON_ITEM_RENDER,
    com.webix.ui.model.Event.ON_KEY_PRESS,
    com.webix.ui.model.Event.ON_LOAD_ERROR,
    com.webix.ui.model.Event.ON_LONG_TOUCH,
    com.webix.ui.model.Event.ON_MENU_ITEM_CLICK,
    com.webix.ui.model.Event.ON_MOUSE_MOVE,
    com.webix.ui.model.Event.ON_MOUSE_MOVING,
    com.webix.ui.model.Event.ON_MOUSE_OUT,
    com.webix.ui.model.Event.ON_PASTE,
    com.webix.ui.model.Event.ON_SELECT_CHANGE,
    com.webix.ui.model.Event.ON_SHOW,
    com.webix.ui.model.Event.ON_SWIPE_X,
    com.webix.ui.model.Event.ON_SWIPE_Y,
    com.webix.ui.model.Event.ON_TIMED_KEY_PRESS,
    com.webix.ui.model.Event.ON_TOUCH_END,
    com.webix.ui.model.Event.ON_TOUCH_MOVE,
    com.webix.ui.model.Event.ON_TOUCH_START,
    com.webix.ui.model.Event.ON_VALIDATION_ERROR,
    com.webix.ui.model.Event.ON_VALIDATION_SUCCESS,
    com.webix.ui.model.Event.ON_VIEW_MOVE,
    com.webix.ui.model.Event.ON_VIEW_MOVE_END,
    com.webix.ui.model.Event.ON_VIEW_RESIZE
})
@com.webix.ui.model.WebixName("contextmenu")
@javax.xml.bind.annotation.XmlRootElement
public class Contextmenu
    extends View
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Adjusts window size to the size of an html node it is
     * initiated in<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autofit_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool")
    private Boolean autofit;

    /**
     * Sets focus on the window the moment it appears on the
     * page<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autofocus_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool")
    private Boolean autofocus;

    /**
     * Height of view will be adjusted to show all items<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autoheight_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool")
    private Boolean autoheight;

    /**
     * Width of view will be adjusted to show all items<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autowidth_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool")
    private Boolean autowidth;

    /**
     * The content of window body: template or view<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_body_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string|view")
    private View body;

    /**
     * Enables/disables clipboard support<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_clipboard_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool|string")
    private String clipboard;

    /**
     * Enables or disables drag-and-drop<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_drag_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool|string")
    private String drag;

    /**
     * Enables autoscroll of component during drag-n-drop<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_dragscroll_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool|string")
    private String dragscroll;

    /**
     * Allows defining custom 'move' logic for the component.<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_externaldata_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("function")
    private String externalData;

    /**
     * Sets the view header<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_head_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("object|string")
    private String head;

    /**
     * Defines the header height (43 by default)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_headheight_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer headHeight;

    /**
     * Defines x or y orientation of layout<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_layout_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string")
    private String layout;

    /**
     * The left offset of the window<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_left_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer left;

    /**
     * The area for which context object in inited<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_master_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string")
    private String master;

    /**
     * Switches window modality<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_modal_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool")
    private Boolean modal;

    /**
     * The delay between a real mouse action and invoking the
     * related events<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_mouseeventdelay_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer mouseEventDelay;

    /**
     * Makes view movable<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_move_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool")
    private Boolean move;

    /**
     * Activates the selection keyboard navigation<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_navigation_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool")
    private Boolean navigation;

    /**
     * Attaches a click behavior for component items with the
     * specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_onclick_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("hash")
    private java.util.Map<String, String> onClick;

    /**
     * A property used to define custom context-click (right click)
     * handlers for elements in the DataTable cells<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_oncontext_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("hash")
    private java.util.Map<String, String> onContext;

    /**
     * Attaches a dblclick behavior for component items with the
     * specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_ondblclick_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("function")
    private java.util.Map<String, String> onDblClick;

    /**
     * Attaches a mousemove behaviour for component items with the
     * specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_onmousemove_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("function")
    private java.util.Map<String, String> onMouseMove;

    /**
     * Sets paddings of the chart content<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_padding_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("object")
    private PaddingConfig padding;

    /**
     * Sets position of the window relative to the the screen<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_position_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string|function")
    private String position;

    /**
     * Positions a popup window relative to the component it's
     * connected with<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_relative_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string")
    private String relative;

    /**
     * Enables/disables the scroll bar<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_scroll_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool|string")
    private String scroll;

    /**
     * The time during which the component is scrolled to the
     * specified position (in milliseconds)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_scrollspeed_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string")
    private String scrollSpeed;

    /**
     * Enables/disables item selection or multiselection in
     * grouplist<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_select_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool|string")
    private String select;

    /**
     * Aligns submenu towards main menu<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_submenupos_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string")
    private String subMenuPos;

    /**
     * Defines submenu configuration<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_submenu_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("object")
    private Menu submenu;

    /**
     * Sets the template according to which data will be copied to
     * the clipboard<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_templatecopy_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("function")
    private String templateCopy;

    /**
     * The top offset of a window<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_top_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer top;

    /**
     * Defines width of view in items<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_xcount_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("int")
    private Integer xCount;

    /**
     * Defines height of view in items<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_ycount_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer yCount;

    /**
     * Stack order of the component<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_zindex_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer zIndex;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the content of window body: template or view<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_body_config.html">Webix
     * API Reference</a>
     * 
     * @return View
     */
    public View getBody()
    {
        return this.body;
    } //-- View getBody()

    /**
     * Get enables/disables clipboard support<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_clipboard_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getClipboard()
    {
        return this.clipboard;
    } //-- String getClipboard()

    /**
     * Get enables or disables drag-and-drop<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_drag_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getDrag()
    {
        return this.drag;
    } //-- String getDrag()

    /**
     * Get enables autoscroll of component during drag-n-drop<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_dragscroll_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getDragscroll()
    {
        return this.dragscroll;
    } //-- String getDragscroll()

    /**
     * Get allows defining custom 'move' logic for the
     * component.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_externaldata_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getExternalData()
    {
        return this.externalData;
    } //-- String getExternalData()

    /**
     * Get sets the view header<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_head_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getHead()
    {
        return this.head;
    } //-- String getHead()

    /**
     * Get defines the header height (43 by default)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_headheight_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getHeadHeight()
    {
        return this.headHeight;
    } //-- Integer getHeadHeight()

    /**
     * Get defines x or y orientation of layout<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_layout_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getLayout()
    {
        return this.layout;
    } //-- String getLayout()

    /**
     * Get the left offset of the window<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_left_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getLeft()
    {
        return this.left;
    } //-- Integer getLeft()

    /**
     * Get the area for which context object in inited<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_master_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getMaster()
    {
        return this.master;
    } //-- String getMaster()

    /**
     * Get the delay between a real mouse action and invoking the
     * related events<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_mouseeventdelay_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getMouseEventDelay()
    {
        return this.mouseEventDelay;
    } //-- Integer getMouseEventDelay()

    /**
     * Get attaches a click behavior for component items with the
     * specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_onclick_config.html">Webix
     * API Reference</a>
     * 
     * @return java.util.Map<String, String>
     */
    public java.util.Map<String, String> getOnClick()
    {
        return this.onClick;
    } //-- java.util.Map<String, String> getOnClick()

    /**
     * Get a property used to define custom context-click (right
     * click) handlers for elements in the DataTable cells<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_oncontext_config.html">Webix
     * API Reference</a>
     * 
     * @return java.util.Map<String, String>
     */
    public java.util.Map<String, String> getOnContext()
    {
        return this.onContext;
    } //-- java.util.Map<String, String> getOnContext()

    /**
     * Get attaches a dblclick behavior for component items with
     * the specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_ondblclick_config.html">Webix
     * API Reference</a>
     * 
     * @return java.util.Map<String, String>
     */
    public java.util.Map<String, String> getOnDblClick()
    {
        return this.onDblClick;
    } //-- java.util.Map<String, String> getOnDblClick()

    /**
     * Get attaches a mousemove behaviour for component items with
     * the specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_onmousemove_config.html">Webix
     * API Reference</a>
     * 
     * @return java.util.Map<String, String>
     */
    public java.util.Map<String, String> getOnMouseMove()
    {
        return this.onMouseMove;
    } //-- java.util.Map<String, String> getOnMouseMove()

    /**
     * Get sets paddings of the chart content<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_padding_config.html">Webix
     * API Reference</a>
     * 
     * @return PaddingConfig
     */
    public PaddingConfig getPadding()
    {
        return this.padding;
    } //-- PaddingConfig getPadding()

    /**
     * Get sets position of the window relative to the the
     * screen<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_position_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getPosition()
    {
        return this.position;
    } //-- String getPosition()

    /**
     * Get positions a popup window relative to the component it's
     * connected with<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_relative_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getRelative()
    {
        return this.relative;
    } //-- String getRelative()

    /**
     * Get enables/disables the scroll bar<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_scroll_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getScroll()
    {
        return this.scroll;
    } //-- String getScroll()

    /**
     * Get the time during which the component is scrolled to the
     * specified position (in milliseconds)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_scrollspeed_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getScrollSpeed()
    {
        return this.scrollSpeed;
    } //-- String getScrollSpeed()

    /**
     * Get enables/disables item selection or multiselection in
     * grouplist<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_select_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getSelect()
    {
        return this.select;
    } //-- String getSelect()

    /**
     * Get aligns submenu towards main menu<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_submenupos_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getSubMenuPos()
    {
        return this.subMenuPos;
    } //-- String getSubMenuPos()

    /**
     * Get defines submenu configuration<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_submenu_config.html">Webix
     * API Reference</a>
     * 
     * @return Menu
     */
    public Menu getSubmenu()
    {
        return this.submenu;
    } //-- Menu getSubmenu()

    /**
     * Get sets the template according to which data will be copied
     * to the clipboard<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_templatecopy_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getTemplateCopy()
    {
        return this.templateCopy;
    } //-- String getTemplateCopy()

    /**
     * Get the top offset of a window<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_top_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getTop()
    {
        return this.top;
    } //-- Integer getTop()

    /**
     * Get defines width of view in items<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_xcount_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getXCount()
    {
        return this.xCount;
    } //-- Integer getXCount()

    /**
     * Get defines height of view in items<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_ycount_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getYCount()
    {
        return this.yCount;
    } //-- Integer getYCount()

    /**
     * Get stack order of the component<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_zindex_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getZIndex()
    {
        return this.zIndex;
    } //-- Integer getZIndex()

    /**
     * Get adjusts window size to the size of an html node it is
     * initiated in<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autofit_config.html">Webix
     * API Reference</a>
     * 
     * @return Boolean
     */
    public Boolean isAutofit()
    {
        return this.autofit;
    } //-- Boolean isAutofit()

    /**
     * Get sets focus on the window the moment it appears on the
     * page<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autofocus_config.html">Webix
     * API Reference</a>
     * 
     * @return Boolean
     */
    public Boolean isAutofocus()
    {
        return this.autofocus;
    } //-- Boolean isAutofocus()

    /**
     * Get height of view will be adjusted to show all items<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autoheight_config.html">Webix
     * API Reference</a>
     * 
     * @return Boolean
     */
    public Boolean isAutoheight()
    {
        return this.autoheight;
    } //-- Boolean isAutoheight()

    /**
     * Get width of view will be adjusted to show all items<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autowidth_config.html">Webix
     * API Reference</a>
     * 
     * @return Boolean
     */
    public Boolean isAutowidth()
    {
        return this.autowidth;
    } //-- Boolean isAutowidth()

    /**
     * Get switches window modality<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_modal_config.html">Webix
     * API Reference</a>
     * 
     * @return Boolean
     */
    public Boolean isModal()
    {
        return this.modal;
    } //-- Boolean isModal()

    /**
     * Get makes view movable<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_move_config.html">Webix
     * API Reference</a>
     * 
     * @return Boolean
     */
    public Boolean isMove()
    {
        return this.move;
    } //-- Boolean isMove()

    /**
     * Get activates the selection keyboard navigation<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_navigation_config.html">Webix
     * API Reference</a>
     * 
     * @return Boolean
     */
    public Boolean isNavigation()
    {
        return this.navigation;
    } //-- Boolean isNavigation()

    /**
     * Set adjusts window size to the size of an html node it is
     * initiated in<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autofit_config.html">Webix
     * API Reference</a>
     * 
     * @param autofit
     */
    public void setAutofit( Boolean autofit )
    {
        this.autofit = autofit;
    } //-- void setAutofit( Boolean )

    /**
     * Set sets focus on the window the moment it appears on the
     * page<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autofocus_config.html">Webix
     * API Reference</a>
     * 
     * @param autofocus
     */
    public void setAutofocus( Boolean autofocus )
    {
        this.autofocus = autofocus;
    } //-- void setAutofocus( Boolean )

    /**
     * Set height of view will be adjusted to show all items<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autoheight_config.html">Webix
     * API Reference</a>
     * 
     * @param autoheight
     */
    public void setAutoheight( Boolean autoheight )
    {
        this.autoheight = autoheight;
    } //-- void setAutoheight( Boolean )

    /**
     * Set width of view will be adjusted to show all items<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_autowidth_config.html">Webix
     * API Reference</a>
     * 
     * @param autowidth
     */
    public void setAutowidth( Boolean autowidth )
    {
        this.autowidth = autowidth;
    } //-- void setAutowidth( Boolean )

    /**
     * Set the content of window body: template or view<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_body_config.html">Webix
     * API Reference</a>
     * 
     * @param body
     */
    public void setBody( View body )
    {
        this.body = body;
    } //-- void setBody( View )

    /**
     * Set enables/disables clipboard support<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_clipboard_config.html">Webix
     * API Reference</a>
     * 
     * @param clipboard
     */
    public void setClipboard( String clipboard )
    {
        this.clipboard = clipboard;
    } //-- void setClipboard( String )

    /**
     * Set enables or disables drag-and-drop<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_drag_config.html">Webix
     * API Reference</a>
     * 
     * @param drag
     */
    public void setDrag( String drag )
    {
        this.drag = drag;
    } //-- void setDrag( String )

    /**
     * Set enables autoscroll of component during drag-n-drop<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_dragscroll_config.html">Webix
     * API Reference</a>
     * 
     * @param dragscroll
     */
    public void setDragscroll( String dragscroll )
    {
        this.dragscroll = dragscroll;
    } //-- void setDragscroll( String )

    /**
     * Set allows defining custom 'move' logic for the
     * component.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_externaldata_config.html">Webix
     * API Reference</a>
     * 
     * @param externalData
     */
    public void setExternalData( String externalData )
    {
        this.externalData = externalData;
    } //-- void setExternalData( String )

    /**
     * Set sets the view header<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_head_config.html">Webix
     * API Reference</a>
     * 
     * @param head
     */
    public void setHead( String head )
    {
        this.head = head;
    } //-- void setHead( String )

    /**
     * Set defines the header height (43 by default)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_headheight_config.html">Webix
     * API Reference</a>
     * 
     * @param headHeight
     */
    public void setHeadHeight( Integer headHeight )
    {
        this.headHeight = headHeight;
    } //-- void setHeadHeight( Integer )

    /**
     * Set defines x or y orientation of layout<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_layout_config.html">Webix
     * API Reference</a>
     * 
     * @param layout
     */
    public void setLayout( String layout )
    {
        this.layout = layout;
    } //-- void setLayout( String )

    /**
     * Set the left offset of the window<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_left_config.html">Webix
     * API Reference</a>
     * 
     * @param left
     */
    public void setLeft( Integer left )
    {
        this.left = left;
    } //-- void setLeft( Integer )

    /**
     * Set the area for which context object in inited<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_master_config.html">Webix
     * API Reference</a>
     * 
     * @param master
     */
    public void setMaster( String master )
    {
        this.master = master;
    } //-- void setMaster( String )

    /**
     * Set switches window modality<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_modal_config.html">Webix
     * API Reference</a>
     * 
     * @param modal
     */
    public void setModal( Boolean modal )
    {
        this.modal = modal;
    } //-- void setModal( Boolean )

    /**
     * Set the delay between a real mouse action and invoking the
     * related events<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_mouseeventdelay_config.html">Webix
     * API Reference</a>
     * 
     * @param mouseEventDelay
     */
    public void setMouseEventDelay( Integer mouseEventDelay )
    {
        this.mouseEventDelay = mouseEventDelay;
    } //-- void setMouseEventDelay( Integer )

    /**
     * Set makes view movable<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_move_config.html">Webix
     * API Reference</a>
     * 
     * @param move
     */
    public void setMove( Boolean move )
    {
        this.move = move;
    } //-- void setMove( Boolean )

    /**
     * Set activates the selection keyboard navigation<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_navigation_config.html">Webix
     * API Reference</a>
     * 
     * @param navigation
     */
    public void setNavigation( Boolean navigation )
    {
        this.navigation = navigation;
    } //-- void setNavigation( Boolean )

    /**
     * Set attaches a click behavior for component items with the
     * specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_onclick_config.html">Webix
     * API Reference</a>
     * 
     * @param onClick
     */
    public void setOnClick( java.util.Map<String, String> onClick )
    {
        this.onClick = onClick;
    } //-- void setOnClick( java.util.Map<String, String> )

    /**
     * Set a property used to define custom context-click (right
     * click) handlers for elements in the DataTable cells<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_oncontext_config.html">Webix
     * API Reference</a>
     * 
     * @param onContext
     */
    public void setOnContext( java.util.Map<String, String> onContext )
    {
        this.onContext = onContext;
    } //-- void setOnContext( java.util.Map<String, String> )

    /**
     * Set attaches a dblclick behavior for component items with
     * the specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_ondblclick_config.html">Webix
     * API Reference</a>
     * 
     * @param onDblClick
     */
    public void setOnDblClick( java.util.Map<String, String> onDblClick )
    {
        this.onDblClick = onDblClick;
    } //-- void setOnDblClick( java.util.Map<String, String> )

    /**
     * Set attaches a mousemove behaviour for component items with
     * the specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_onmousemove_config.html">Webix
     * API Reference</a>
     * 
     * @param onMouseMove
     */
    public void setOnMouseMove( java.util.Map<String, String> onMouseMove )
    {
        this.onMouseMove = onMouseMove;
    } //-- void setOnMouseMove( java.util.Map<String, String> )

    /**
     * Set sets paddings of the chart content<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_padding_config.html">Webix
     * API Reference</a>
     * 
     * @param padding
     */
    public void setPadding( PaddingConfig padding )
    {
        this.padding = padding;
    } //-- void setPadding( PaddingConfig )

    /**
     * Set sets position of the window relative to the the
     * screen<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_position_config.html">Webix
     * API Reference</a>
     * 
     * @param position
     */
    public void setPosition( String position )
    {
        this.position = position;
    } //-- void setPosition( String )

    /**
     * Set positions a popup window relative to the component it's
     * connected with<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_relative_config.html">Webix
     * API Reference</a>
     * 
     * @param relative
     */
    public void setRelative( String relative )
    {
        this.relative = relative;
    } //-- void setRelative( String )

    /**
     * Set enables/disables the scroll bar<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_scroll_config.html">Webix
     * API Reference</a>
     * 
     * @param scroll
     */
    public void setScroll( String scroll )
    {
        this.scroll = scroll;
    } //-- void setScroll( String )

    /**
     * Set the time during which the component is scrolled to the
     * specified position (in milliseconds)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_scrollspeed_config.html">Webix
     * API Reference</a>
     * 
     * @param scrollSpeed
     */
    public void setScrollSpeed( String scrollSpeed )
    {
        this.scrollSpeed = scrollSpeed;
    } //-- void setScrollSpeed( String )

    /**
     * Set enables/disables item selection or multiselection in
     * grouplist<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_select_config.html">Webix
     * API Reference</a>
     * 
     * @param select
     */
    public void setSelect( String select )
    {
        this.select = select;
    } //-- void setSelect( String )

    /**
     * Set aligns submenu towards main menu<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_submenupos_config.html">Webix
     * API Reference</a>
     * 
     * @param subMenuPos
     */
    public void setSubMenuPos( String subMenuPos )
    {
        this.subMenuPos = subMenuPos;
    } //-- void setSubMenuPos( String )

    /**
     * Set defines submenu configuration<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_submenu_config.html">Webix
     * API Reference</a>
     * 
     * @param submenu
     */
    public void setSubmenu( Menu submenu )
    {
        this.submenu = submenu;
    } //-- void setSubmenu( Menu )

    /**
     * Set sets the template according to which data will be copied
     * to the clipboard<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_templatecopy_config.html">Webix
     * API Reference</a>
     * 
     * @param templateCopy
     */
    public void setTemplateCopy( String templateCopy )
    {
        this.templateCopy = templateCopy;
    } //-- void setTemplateCopy( String )

    /**
     * Set the top offset of a window<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_top_config.html">Webix
     * API Reference</a>
     * 
     * @param top
     */
    public void setTop( Integer top )
    {
        this.top = top;
    } //-- void setTop( Integer )

    /**
     * Set defines width of view in items<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_xcount_config.html">Webix
     * API Reference</a>
     * 
     * @param xCount
     */
    public void setXCount( Integer xCount )
    {
        this.xCount = xCount;
    } //-- void setXCount( Integer )

    /**
     * Set defines height of view in items<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_ycount_config.html">Webix
     * API Reference</a>
     * 
     * @param yCount
     */
    public void setYCount( Integer yCount )
    {
        this.yCount = yCount;
    } //-- void setYCount( Integer )

    /**
     * Set stack order of the component<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.contextmenu_zindex_config.html">Webix
     * API Reference</a>
     * 
     * @param zIndex
     */
    public void setZIndex( Integer zIndex )
    {
        this.zIndex = zIndex;
    } //-- void setZIndex( Integer )

}
