// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.3,
// any modifications will be overwritten.
// ==============================================================

package com.webix.ui.model.layouts;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import com.webix.ui.model.AnimateConfig;
import com.webix.ui.model.Baselayout;
import com.webix.ui.model.Baseview;
import com.webix.ui.model.DelimiterConfig;
import com.webix.ui.model.EventHandler;
import com.webix.ui.model.EventHandlerList;
import com.webix.ui.model.GraphItemConfig;
import com.webix.ui.model.NavigationConfig;
import com.webix.ui.model.PaddingConfig;
import com.webix.ui.model.Proto;
import com.webix.ui.model.RGBColorList;
import com.webix.ui.model.TypeConfig;
import com.webix.ui.model.UnknownType;
import com.webix.ui.model.View;
import com.webix.ui.model.auxiliary.Calendar;
import com.webix.ui.model.auxiliary.Colorboard;
import com.webix.ui.model.auxiliary.Pager;
import com.webix.ui.model.auxiliary.Resizer;
import com.webix.ui.model.auxiliary.Spacer;
import com.webix.ui.model.auxiliary.Tooltip;
import com.webix.ui.model.auxiliary.Video;
import com.webix.ui.model.context.Context;
import com.webix.ui.model.context.Contextmenu;
import com.webix.ui.model.context.Datasuggest;
import com.webix.ui.model.context.Gridsuggest;
import com.webix.ui.model.context.Menu;
import com.webix.ui.model.context.Popup;
import com.webix.ui.model.context.Submenu;
import com.webix.ui.model.context.Suggest;
import com.webix.ui.model.context.Window;
import com.webix.ui.model.data.Chart;
import com.webix.ui.model.data.Datatable;
import com.webix.ui.model.data.Dataview;
import com.webix.ui.model.data.Grouplist;
import com.webix.ui.model.data.List;
import com.webix.ui.model.data.Property;
import com.webix.ui.model.data.Tree;
import com.webix.ui.model.data.Treetable;
import com.webix.ui.model.data.Unitlist;
import com.webix.ui.model.form.Button;
import com.webix.ui.model.form.Checkbox;
import com.webix.ui.model.form.Colorpicker;
import com.webix.ui.model.form.Combo;
import com.webix.ui.model.form.Counter;
import com.webix.ui.model.form.Datepicker;
import com.webix.ui.model.form.Fieldset;
import com.webix.ui.model.form.Icon;
import com.webix.ui.model.form.Label;
import com.webix.ui.model.form.Multiselect;
import com.webix.ui.model.form.Multitext;
import com.webix.ui.model.form.Radio;
import com.webix.ui.model.form.Richselect;
import com.webix.ui.model.form.Search;
import com.webix.ui.model.form.Segmented;
import com.webix.ui.model.form.Select;
import com.webix.ui.model.form.Slider;
import com.webix.ui.model.form.Tabbar;
import com.webix.ui.model.form.Text;
import com.webix.ui.model.form.Textarea;
import com.webix.ui.model.form.Toggle;
import com.webix.ui.model.html.Htmlform;
import com.webix.ui.model.html.Iframe;
import com.webix.ui.model.html.Scrollview;
import com.webix.ui.model.html.Template;





/**
 * 
 * A container control that provides continuous, circular
 * navigation through a set of pictorial content blocks. One block
 * is visible at a time.
 * The control supports any content inside of it. The content
 * blocks can be arranged vertically or horizontally, supplemented
 * or not with the navigation control panel. Check <a
 * href="http://docs.webix.com/desktop__carousel.html">carousel</a>
 * documentation for more detailed description.
 * 
 * 
 * @version $Revision$ $Date$
 */
@com.webix.ui.model.WebixEvent({
    com.webix.ui.model.Event.ON_AFTER_SCROLL,
    com.webix.ui.model.Event.ON_BIND_REQUEST,
    com.webix.ui.model.Event.ON_DESTRUCT,
    com.webix.ui.model.Event.ON_KEY_PRESS,
    com.webix.ui.model.Event.ON_LONG_TOUCH,
    com.webix.ui.model.Event.ON_SHOW,
    com.webix.ui.model.Event.ON_SWIPE_X,
    com.webix.ui.model.Event.ON_SWIPE_Y,
    com.webix.ui.model.Event.ON_TIMED_KEY_PRESS,
    com.webix.ui.model.Event.ON_TOUCH_END,
    com.webix.ui.model.Event.ON_TOUCH_MOVE,
    com.webix.ui.model.Event.ON_TOUCH_START,
    com.webix.ui.model.Event.ON_VIEW_RESIZE
})
@com.webix.ui.model.WebixName("carousel")
@javax.xml.bind.annotation.XmlRootElement
public class Carousel
    extends Baselayout
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Defines navigation parameters<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.carousel_navigation_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("object")
    private NavigationConfig navigation;

    /**
     * Field rows.
     */
    @com.webix.ui.model.WebixType("array")
    private java.util.List<View> rows;

    /**
     * Speed of scrolling ('300ms' by default)<br /><br /><a
     * href="http://docs.webix.com/api__ui.carousel_scrollspeed_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string")
    private String scrollSpeed;

    /**
     * Defines the layout borders<br /><br /><a
     * href="http://docs.webix.com/api__ui.carousel_type_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string")
    private String type;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get defines navigation parameters<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.carousel_navigation_config.html">Webix
     * API Reference</a>
     * 
     * @return NavigationConfig
     */
    public NavigationConfig getNavigation()
    {
        return this.navigation;
    } //-- NavigationConfig getNavigation()

    /**
     * Method getRows.
     * 
     * @return List
     */
    public java.util.List<View> getRows()
    {
        if ( this.rows == null )
        {
            this.rows = new java.util.ArrayList<View>();
        }

        return this.rows;
    } //-- java.util.List<View> getRows()

    /**
     * Get speed of scrolling ('300ms' by default)<br /><br /><a
     * href="http://docs.webix.com/api__ui.carousel_scrollspeed_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getScrollSpeed()
    {
        return this.scrollSpeed;
    } //-- String getScrollSpeed()

    /**
     * Get defines the layout borders<br /><br /><a
     * href="http://docs.webix.com/api__ui.carousel_type_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getType()
    {
        return this.type;
    } //-- String getType()

    /**
     * Set defines navigation parameters<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.carousel_navigation_config.html">Webix
     * API Reference</a>
     * 
     * @param navigation
     */
    public void setNavigation( NavigationConfig navigation )
    {
        this.navigation = navigation;
    } //-- void setNavigation( NavigationConfig )

    /**
     * Set array of views arranged vertically<br /><br /><a
     * href="http://docs.webix.com/api__ui.carousel_rows_config.html">Webix
     * API Reference</a>
     * 
     * @param rows
     */
    public void setRows( java.util.List<View> rows )
    {
        this.rows = rows;
    } //-- void setRows( java.util.List )

    /**
     * Set speed of scrolling ('300ms' by default)<br /><br /><a
     * href="http://docs.webix.com/api__ui.carousel_scrollspeed_config.html">Webix
     * API Reference</a>
     * 
     * @param scrollSpeed
     */
    public void setScrollSpeed( String scrollSpeed )
    {
        this.scrollSpeed = scrollSpeed;
    } //-- void setScrollSpeed( String )

    /**
     * Set defines the layout borders<br /><br /><a
     * href="http://docs.webix.com/api__ui.carousel_type_config.html">Webix
     * API Reference</a>
     * 
     * @param type
     */
    public void setType( String type )
    {
        this.type = type;
    } //-- void setType( String )

}
