// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package com.webix.ui.model.layouts;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import com.webix.ui.model.UnknownType;
import com.webix.ui.model.auxiliary.Calendar;
import com.webix.ui.model.auxiliary.Colorboard;
import com.webix.ui.model.auxiliary.Pager;
import com.webix.ui.model.auxiliary.Resizer;
import com.webix.ui.model.auxiliary.Spacer;
import com.webix.ui.model.auxiliary.Tooltip;
import com.webix.ui.model.auxiliary.Video;
import com.webix.ui.model.context.Context;
import com.webix.ui.model.context.Contextmenu;
import com.webix.ui.model.context.Datasuggest;
import com.webix.ui.model.context.Gridsuggest;
import com.webix.ui.model.context.Menu;
import com.webix.ui.model.context.Popup;
import com.webix.ui.model.context.Submenu;
import com.webix.ui.model.context.Suggest;
import com.webix.ui.model.context.Window;
import com.webix.ui.model.data.Chart;
import com.webix.ui.model.data.Datatable;
import com.webix.ui.model.data.Dataview;
import com.webix.ui.model.data.Grouplist;
import com.webix.ui.model.data.List;
import com.webix.ui.model.data.Property;
import com.webix.ui.model.data.Tree;
import com.webix.ui.model.data.Treetable;
import com.webix.ui.model.data.Unitlist;
import com.webix.ui.model.form.Button;
import com.webix.ui.model.form.Checkbox;
import com.webix.ui.model.form.Colorpicker;
import com.webix.ui.model.form.Combo;
import com.webix.ui.model.form.Counter;
import com.webix.ui.model.form.Datepicker;
import com.webix.ui.model.form.Fieldset;
import com.webix.ui.model.form.Icon;
import com.webix.ui.model.form.Label;
import com.webix.ui.model.form.Multiselect;
import com.webix.ui.model.form.Multitext;
import com.webix.ui.model.form.Radio;
import com.webix.ui.model.form.Richselect;
import com.webix.ui.model.form.Search;
import com.webix.ui.model.form.Segmented;
import com.webix.ui.model.form.Select;
import com.webix.ui.model.form.Slider;
import com.webix.ui.model.form.Tabbar;
import com.webix.ui.model.form.Text;
import com.webix.ui.model.form.Textarea;
import com.webix.ui.model.form.Toggle;
import com.webix.ui.model.html.Htmlform;
import com.webix.ui.model.html.Iframe;
import com.webix.ui.model.html.Scrollview;
import com.webix.ui.model.html.Template;

/**
 * A form that supports an extended set of elements.The component
 * provides validation and the ability to save user input to the
 * backend database. Check <a
 * href="http://docs.webix.com/desktop__form.html">form</a>
 * documentation for more detailed description.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
@com.webix.ui.model.SupportsEvent({com.webix.ui.model.Event.ON_AFTER_LOAD, com.webix.ui.model.Event.ON_AFTER_VALIDATION, com.webix.ui.model.Event.ON_BEFORE_LOAD, com.webix.ui.model.Event.ON_BEFORE_VALIDATE, com.webix.ui.model.Event.ON_BIND_REQUEST, com.webix.ui.model.Event.ON_CHANGE, com.webix.ui.model.Event.ON_DESTRUCT, com.webix.ui.model.Event.ON_LOAD_ERROR, com.webix.ui.model.Event.ON_SUBMIT, com.webix.ui.model.Event.ON_VALIDATION_ERROR, com.webix.ui.model.Event.ON_VALIDATION_SUCCESS})
public class Form
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Defines or disables view change animation.
     */
    private UnknownType animate;

    /**
     * Sets component height according to its contents.
     */
    private Boolean autoheight;

    /**
     * Used to hide the component borders.
     */
    private Boolean borderless;

    /**
     * Field cols.
     */
    private java.util.List<UnknownType> cols;

    /**
     * An html container (or its id) where the component needs
     * initializing.
     */
    private UnknownType container;

    /**
     * The name of a css class that will be applied to the view
     * container.
     */
    private String css;

    /**
     * An inline dataset that data to the component will be load
     * from.
     */
    private UnknownType data;

    /**
     * The url to the data source that the component will use to
     * reload data from.
     */
    private UnknownType dataFeed;

    /**
     * The type of loaded data.
     */
    private String datatype;

    /**
     * Disables item.
     */
    private Boolean disabled;

    /**
     * Field elements.
     */
    private java.util.List<UnknownType> elements;

    /**
     * Settings, which will be applied to all nested inputs.
     */
    private UnknownType elementsConfig;

    /**
     * Sets the view gravity (1 by default).
     */
    private Integer gravity;

    /**
     * Sets the height of the component.
     */
    private Integer height;

    /**
     * Defines whether the view will be hidden initially.
     */
    private Boolean hidden;

    /**
     * The component ID.
     */
    private String id;

    /**
     * Masks IDs of all inner element.
     */
    private Boolean isolate;

    /**
     * Defines the space around elements (applies the specified
     * value to all elements).
     */
    private Integer margin;

    /**
     * Sets the maximum height for the view.
     */
    private Integer maxHeight;

    /**
     * Sets the maximum width for the view.
     */
    private Integer maxWidth;

    /**
     * Sets the minimal height for the view.
     */
    private Integer minHeight;

    /**
     * Sets the minimal width for the view.
     */
    private Integer minWidth;

    /**
     * Allows attaching custom handlers to inner events of the
     * component.
     */
    private UnknownType on;

    /**
     * Defines the space between the element borders and content
     * (applies the specified value to all sides).
     */
    private Integer padding;

    /**
     * Sets the right and left padding (applies the specified value
     * to both sides).
     */
    private Integer paddingX;

    /**
     * Sets the top and bottom padding (applies the specified value
     * to both sides).
     */
    private Integer paddingY;

    /**
     * Enables responsive mode for horizontal layout.
     */
    private String responsive;

    /**
     * Field rows.
     */
    private java.util.List<UnknownType> rows;

    /**
     * Defines a set of rules for input field(s) of the
     * form(htmlform).
     */
    private UnknownType rules;

    /**
     * Enables/disables the scroll bar.
     */
    private UnknownType scroll;

    /**
     * The time during which the component is scrolled to the
     * specified position (in milliseconds).
     */
    private String scrollSpeed;

    /**
     * Defines the layout borders.
     */
    private String type;

    /**
     * The url of a data feed which will be loaded after component
     * initialization.
     */
    private String url;

    /**
     * Sets the batch that will be shown initially.
     */
    private String visibleBatch;

    /**
     * Sets the width of the component.
     */
    private Integer width;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addCol.
     * 
     * @param unknownType
     */
    public void addCol( UnknownType unknownType )
    {
        getCols().add( unknownType );
    } //-- void addCol( UnknownType )

    /**
     * Method addElement.
     * 
     * @param unknownType
     */
    public void addElement( UnknownType unknownType )
    {
        getElements().add( unknownType );
    } //-- void addElement( UnknownType )

    /**
     * Method addRow.
     * 
     * @param unknownType
     */
    public void addRow( UnknownType unknownType )
    {
        getRows().add( unknownType );
    } //-- void addRow( UnknownType )

    /**
     * Get defines or disables view change animation.
     * 
     * @return UnknownType
     */
    public UnknownType getAnimate()
    {
        return this.animate;
    } //-- UnknownType getAnimate()

    /**
     * Method getCols.
     * 
     * @return List
     */
    public java.util.List<UnknownType> getCols()
    {
        if ( this.cols == null )
        {
            this.cols = new java.util.ArrayList<UnknownType>();
        }

        return this.cols;
    } //-- java.util.List<UnknownType> getCols()

    /**
     * Get an html container (or its id) where the component needs
     * initializing.
     * 
     * @return UnknownType
     */
    public UnknownType getContainer()
    {
        return this.container;
    } //-- UnknownType getContainer()

    /**
     * Get the name of a css class that will be applied to the view
     * container.
     * 
     * @return String
     */
    public String getCss()
    {
        return this.css;
    } //-- String getCss()

    /**
     * Get an inline dataset that data to the component will be
     * load from.
     * 
     * @return UnknownType
     */
    public UnknownType getData()
    {
        return this.data;
    } //-- UnknownType getData()

    /**
     * Get the url to the data source that the component will use
     * to reload data from.
     * 
     * @return UnknownType
     */
    public UnknownType getDataFeed()
    {
        return this.dataFeed;
    } //-- UnknownType getDataFeed()

    /**
     * Get the type of loaded data.
     * 
     * @return String
     */
    public String getDatatype()
    {
        return this.datatype;
    } //-- String getDatatype()

    /**
     * Method getElements.
     * 
     * @return List
     */
    public java.util.List<UnknownType> getElements()
    {
        if ( this.elements == null )
        {
            this.elements = new java.util.ArrayList<UnknownType>();
        }

        return this.elements;
    } //-- java.util.List<UnknownType> getElements()

    /**
     * Get settings, which will be applied to all nested inputs.
     * 
     * @return UnknownType
     */
    public UnknownType getElementsConfig()
    {
        return this.elementsConfig;
    } //-- UnknownType getElementsConfig()

    /**
     * Get sets the view gravity (1 by default).
     * 
     * @return Integer
     */
    public Integer getGravity()
    {
        return this.gravity;
    } //-- Integer getGravity()

    /**
     * Get sets the height of the component.
     * 
     * @return Integer
     */
    public Integer getHeight()
    {
        return this.height;
    } //-- Integer getHeight()

    /**
     * Get the component ID.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get defines the space around elements (applies the specified
     * value to all elements).
     * 
     * @return Integer
     */
    public Integer getMargin()
    {
        return this.margin;
    } //-- Integer getMargin()

    /**
     * Get sets the maximum height for the view.
     * 
     * @return Integer
     */
    public Integer getMaxHeight()
    {
        return this.maxHeight;
    } //-- Integer getMaxHeight()

    /**
     * Get sets the maximum width for the view.
     * 
     * @return Integer
     */
    public Integer getMaxWidth()
    {
        return this.maxWidth;
    } //-- Integer getMaxWidth()

    /**
     * Get sets the minimal height for the view.
     * 
     * @return Integer
     */
    public Integer getMinHeight()
    {
        return this.minHeight;
    } //-- Integer getMinHeight()

    /**
     * Get sets the minimal width for the view.
     * 
     * @return Integer
     */
    public Integer getMinWidth()
    {
        return this.minWidth;
    } //-- Integer getMinWidth()

    /**
     * Get allows attaching custom handlers to inner events of the
     * component.
     * 
     * @return UnknownType
     */
    public UnknownType getOn()
    {
        return this.on;
    } //-- UnknownType getOn()

    /**
     * Get defines the space between the element borders and
     * content (applies the specified value to all sides).
     * 
     * @return Integer
     */
    public Integer getPadding()
    {
        return this.padding;
    } //-- Integer getPadding()

    /**
     * Get sets the right and left padding (applies the specified
     * value to both sides).
     * 
     * @return Integer
     */
    public Integer getPaddingX()
    {
        return this.paddingX;
    } //-- Integer getPaddingX()

    /**
     * Get sets the top and bottom padding (applies the specified
     * value to both sides).
     * 
     * @return Integer
     */
    public Integer getPaddingY()
    {
        return this.paddingY;
    } //-- Integer getPaddingY()

    /**
     * Get enables responsive mode for horizontal layout.
     * 
     * @return String
     */
    public String getResponsive()
    {
        return this.responsive;
    } //-- String getResponsive()

    /**
     * Method getRows.
     * 
     * @return List
     */
    public java.util.List<UnknownType> getRows()
    {
        if ( this.rows == null )
        {
            this.rows = new java.util.ArrayList<UnknownType>();
        }

        return this.rows;
    } //-- java.util.List<UnknownType> getRows()

    /**
     * Get defines a set of rules for input field(s) of the
     * form(htmlform).
     * 
     * @return UnknownType
     */
    public UnknownType getRules()
    {
        return this.rules;
    } //-- UnknownType getRules()

    /**
     * Get enables/disables the scroll bar.
     * 
     * @return UnknownType
     */
    public UnknownType getScroll()
    {
        return this.scroll;
    } //-- UnknownType getScroll()

    /**
     * Get the time during which the component is scrolled to the
     * specified position (in milliseconds).
     * 
     * @return String
     */
    public String getScrollSpeed()
    {
        return this.scrollSpeed;
    } //-- String getScrollSpeed()

    /**
     * Get defines the layout borders.
     * 
     * @return String
     */
    public String getType()
    {
        return this.type;
    } //-- String getType()

    /**
     * Get the url of a data feed which will be loaded after
     * component initialization.
     * 
     * @return String
     */
    public String getUrl()
    {
        return this.url;
    } //-- String getUrl()

    /**
     * Get sets the batch that will be shown initially.
     * 
     * @return String
     */
    public String getVisibleBatch()
    {
        return this.visibleBatch;
    } //-- String getVisibleBatch()

    /**
     * Get sets the width of the component.
     * 
     * @return Integer
     */
    public Integer getWidth()
    {
        return this.width;
    } //-- Integer getWidth()

    /**
     * Get sets component height according to its contents.
     * 
     * @return Boolean
     */
    public Boolean isAutoheight()
    {
        return this.autoheight;
    } //-- Boolean isAutoheight()

    /**
     * Get used to hide the component borders.
     * 
     * @return Boolean
     */
    public Boolean isBorderless()
    {
        return this.borderless;
    } //-- Boolean isBorderless()

    /**
     * Get disables item.
     * 
     * @return Boolean
     */
    public Boolean isDisabled()
    {
        return this.disabled;
    } //-- Boolean isDisabled()

    /**
     * Get defines whether the view will be hidden initially.
     * 
     * @return Boolean
     */
    public Boolean isHidden()
    {
        return this.hidden;
    } //-- Boolean isHidden()

    /**
     * Get masks IDs of all inner element.
     * 
     * @return Boolean
     */
    public Boolean isIsolate()
    {
        return this.isolate;
    } //-- Boolean isIsolate()

    /**
     * Method removeCol.
     * 
     * @param unknownType
     */
    public void removeCol( UnknownType unknownType )
    {
        getCols().remove( unknownType );
    } //-- void removeCol( UnknownType )

    /**
     * Method removeElement.
     * 
     * @param unknownType
     */
    public void removeElement( UnknownType unknownType )
    {
        getElements().remove( unknownType );
    } //-- void removeElement( UnknownType )

    /**
     * Method removeRow.
     * 
     * @param unknownType
     */
    public void removeRow( UnknownType unknownType )
    {
        getRows().remove( unknownType );
    } //-- void removeRow( UnknownType )

    /**
     * Set defines or disables view change animation.
     * 
     * @param animate
     */
    public void setAnimate( UnknownType animate )
    {
        this.animate = animate;
    } //-- void setAnimate( UnknownType )

    /**
     * Set sets component height according to its contents.
     * 
     * @param autoheight
     */
    public void setAutoheight( Boolean autoheight )
    {
        this.autoheight = autoheight;
    } //-- void setAutoheight( Boolean )

    /**
     * Set used to hide the component borders.
     * 
     * @param borderless
     */
    public void setBorderless( Boolean borderless )
    {
        this.borderless = borderless;
    } //-- void setBorderless( Boolean )

    /**
     * Set array of views objects arranged horizontally.
     * 
     * @param cols
     */
    public void setCols( java.util.List<UnknownType> cols )
    {
        this.cols = cols;
    } //-- void setCols( java.util.List )

    /**
     * Set an html container (or its id) where the component needs
     * initializing.
     * 
     * @param container
     */
    public void setContainer( UnknownType container )
    {
        this.container = container;
    } //-- void setContainer( UnknownType )

    /**
     * Set the name of a css class that will be applied to the view
     * container.
     * 
     * @param css
     */
    public void setCss( String css )
    {
        this.css = css;
    } //-- void setCss( String )

    /**
     * Set an inline dataset that data to the component will be
     * load from.
     * 
     * @param data
     */
    public void setData( UnknownType data )
    {
        this.data = data;
    } //-- void setData( UnknownType )

    /**
     * Set the url to the data source that the component will use
     * to reload data from.
     * 
     * @param dataFeed
     */
    public void setDataFeed( UnknownType dataFeed )
    {
        this.dataFeed = dataFeed;
    } //-- void setDataFeed( UnknownType )

    /**
     * Set the type of loaded data.
     * 
     * @param datatype
     */
    public void setDatatype( String datatype )
    {
        this.datatype = datatype;
    } //-- void setDatatype( String )

    /**
     * Set disables item.
     * 
     * @param disabled
     */
    public void setDisabled( Boolean disabled )
    {
        this.disabled = disabled;
    } //-- void setDisabled( Boolean )

    /**
     * Set collection of subviews.
     * 
     * @param elements
     */
    public void setElements( java.util.List<UnknownType> elements )
    {
        this.elements = elements;
    } //-- void setElements( java.util.List )

    /**
     * Set settings, which will be applied to all nested inputs.
     * 
     * @param elementsConfig
     */
    public void setElementsConfig( UnknownType elementsConfig )
    {
        this.elementsConfig = elementsConfig;
    } //-- void setElementsConfig( UnknownType )

    /**
     * Set sets the view gravity (1 by default).
     * 
     * @param gravity
     */
    public void setGravity( Integer gravity )
    {
        this.gravity = gravity;
    } //-- void setGravity( Integer )

    /**
     * Set sets the height of the component.
     * 
     * @param height
     */
    public void setHeight( Integer height )
    {
        this.height = height;
    } //-- void setHeight( Integer )

    /**
     * Set defines whether the view will be hidden initially.
     * 
     * @param hidden
     */
    public void setHidden( Boolean hidden )
    {
        this.hidden = hidden;
    } //-- void setHidden( Boolean )

    /**
     * Set the component ID.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set masks IDs of all inner element.
     * 
     * @param isolate
     */
    public void setIsolate( Boolean isolate )
    {
        this.isolate = isolate;
    } //-- void setIsolate( Boolean )

    /**
     * Set defines the space around elements (applies the specified
     * value to all elements).
     * 
     * @param margin
     */
    public void setMargin( Integer margin )
    {
        this.margin = margin;
    } //-- void setMargin( Integer )

    /**
     * Set sets the maximum height for the view.
     * 
     * @param maxHeight
     */
    public void setMaxHeight( Integer maxHeight )
    {
        this.maxHeight = maxHeight;
    } //-- void setMaxHeight( Integer )

    /**
     * Set sets the maximum width for the view.
     * 
     * @param maxWidth
     */
    public void setMaxWidth( Integer maxWidth )
    {
        this.maxWidth = maxWidth;
    } //-- void setMaxWidth( Integer )

    /**
     * Set sets the minimal height for the view.
     * 
     * @param minHeight
     */
    public void setMinHeight( Integer minHeight )
    {
        this.minHeight = minHeight;
    } //-- void setMinHeight( Integer )

    /**
     * Set sets the minimal width for the view.
     * 
     * @param minWidth
     */
    public void setMinWidth( Integer minWidth )
    {
        this.minWidth = minWidth;
    } //-- void setMinWidth( Integer )

    /**
     * Set allows attaching custom handlers to inner events of the
     * component.
     * 
     * @param on
     */
    public void setOn( UnknownType on )
    {
        this.on = on;
    } //-- void setOn( UnknownType )

    /**
     * Set defines the space between the element borders and
     * content (applies the specified value to all sides).
     * 
     * @param padding
     */
    public void setPadding( Integer padding )
    {
        this.padding = padding;
    } //-- void setPadding( Integer )

    /**
     * Set sets the right and left padding (applies the specified
     * value to both sides).
     * 
     * @param paddingX
     */
    public void setPaddingX( Integer paddingX )
    {
        this.paddingX = paddingX;
    } //-- void setPaddingX( Integer )

    /**
     * Set sets the top and bottom padding (applies the specified
     * value to both sides).
     * 
     * @param paddingY
     */
    public void setPaddingY( Integer paddingY )
    {
        this.paddingY = paddingY;
    } //-- void setPaddingY( Integer )

    /**
     * Set enables responsive mode for horizontal layout.
     * 
     * @param responsive
     */
    public void setResponsive( String responsive )
    {
        this.responsive = responsive;
    } //-- void setResponsive( String )

    /**
     * Set array of views objects arranged vertically.
     * 
     * @param rows
     */
    public void setRows( java.util.List<UnknownType> rows )
    {
        this.rows = rows;
    } //-- void setRows( java.util.List )

    /**
     * Set defines a set of rules for input field(s) of the
     * form(htmlform).
     * 
     * @param rules
     */
    public void setRules( UnknownType rules )
    {
        this.rules = rules;
    } //-- void setRules( UnknownType )

    /**
     * Set enables/disables the scroll bar.
     * 
     * @param scroll
     */
    public void setScroll( UnknownType scroll )
    {
        this.scroll = scroll;
    } //-- void setScroll( UnknownType )

    /**
     * Set the time during which the component is scrolled to the
     * specified position (in milliseconds).
     * 
     * @param scrollSpeed
     */
    public void setScrollSpeed( String scrollSpeed )
    {
        this.scrollSpeed = scrollSpeed;
    } //-- void setScrollSpeed( String )

    /**
     * Set defines the layout borders.
     * 
     * @param type
     */
    public void setType( String type )
    {
        this.type = type;
    } //-- void setType( String )

    /**
     * Set the url of a data feed which will be loaded after
     * component initialization.
     * 
     * @param url
     */
    public void setUrl( String url )
    {
        this.url = url;
    } //-- void setUrl( String )

    /**
     * Set sets the batch that will be shown initially.
     * 
     * @param visibleBatch
     */
    public void setVisibleBatch( String visibleBatch )
    {
        this.visibleBatch = visibleBatch;
    } //-- void setVisibleBatch( String )

    /**
     * Set sets the width of the component.
     * 
     * @param width
     */
    public void setWidth( Integer width )
    {
        this.width = width;
    } //-- void setWidth( Integer )

    /**
     * Add new view to layout-like component
     */
    public Byte addView() {
        return null;
    }
    /**
     * Adjusts the component to the size of the parent HTML container
     */
    public void adjust() {
        return;
    }
    /**
     * Attaches the handler to an inner event of the component (allows behaviour customizations)
     */
    public Byte attachEvent() {
        return null;
    }
    /**
     * Binds components
     */
    public void bind() {
        return;
    }
    /**
     * Temporarily blocks triggering of ALL events of the calling object
     */
    public void blockEvent() {
        return;
    }
    /**
     * Calls an inner event
     */
    public Boolean callEvent() {
        return null;
    }
    /**
     * Clears all the field in a specified form
     */
    public void clear() {
        return;
    }
    /**
     * Removes "data incorrect" highlighting from invalid text fields
     */
    public void clearValidation() {
        return;
    }
    /**
     * Redefines a single configuration property (or a hash of properties)
     */
    public void define() {
        return;
    }
    /**
     * Destructs the calling object
     */
    public void destructor() {
        return;
    }
    /**
     * Detaches a handler from an event (which was attached before by the attachEvent method)
     */
    public void detachEvent() {
        return;
    }
    /**
     * Disables the calling view (makes it dimmed and unclickable)
     */
    public void disable() {
        return;
    }
    /**
     * Enables the calling view that was disabled by the 'disable' method
     */
    public void enable() {
        return;
    }
    /**
     * Sets focus into the necessary component
     */
    public void focus() {
        return;
    }
    /**
     * Returns child views of the calling component
     */
    public Byte getChildViews() {
        return null;
    }
    /**
     * Returns hash of original form values
     */
    public Byte getCleanValues() {
        return null;
    }
    /**
     * Returns hash of changed values
     */
    public Byte getDirtyValues() {
        return null;
    }
    /**
     * Returns master form for the input
     */
    public Byte getFormView() {
        return null;
    }
    /**
     * Returns the main HTML container for the calling object
     */
    public Byte getNode() {
        return null;
    }
    /**
     * Returns the parent view of the component
     */
    public Byte getParentView() {
        return null;
    }
    /**
     * Returns the scroll position
     */
    public Byte getScrollState() {
        return null;
    }
    /**
     * Returns top parent view
     */
    public Byte getTopParentView() {
        return null;
    }
    /**
     * Derives input values from the form
     */
    public Byte getValues() {
        return null;
    }
    /**
     * Checks whether the component has the specified event
     */
    public Boolean hasEvent() {
        return null;
    }
    /**
     * Hides the view
     */
    public void hide() {
        return;
    }
    /**
     * Returns the cell index in the layout collection
     */
    public Integer index() {
        return null;
    }
    /**
     * Checks whether changes within form were made
     */
    public Boolean isDirty() {
        return null;
    }
    /**
     * Checks whether the view is enabled
     */
    public Boolean isEnabled() {
        return null;
    }
    /**
     * Checks whether the view is visible
     */
    public Boolean isVisible() {
        return null;
    }
    /**
     * Loads data from an external data source
     */
    public Byte load() {
        return null;
    }
    /**
     * Routes events from one object to another
     */
    public void mapEvent() {
        return;
    }
    /**
     * Loads data to the component from an inline data source
     */
    public void parse() {
        return;
    }
    /**
     * Rebuilds the layout
     */
    public void reconstruct() {
        return;
    }
    /**
     * Repaints the component
     */
    public void refresh() {
        return;
    }
    /**
     * Removes view from layout-like component
     */
    public void removeView() {
        return;
    }
    /**
     * Renders the specified item or the whole component
     */
    public void render() {
        return;
    }
    /**
     * Adjusts the view to a new size
     */
    public void resize() {
        return;
    }
    /**
     * Resizes all children of the calling component
     */
    public void resizeChildren() {
        return;
    }
    /**
     * Scrolls the data container to a certain position
     */
    public void scrollTo() {
        return;
    }
    /**
     * Marks the form as the one with changed values and vice versa
     */
    public void setDirty() {
        return;
    }
    /**
     * Sets values into all the form inputs
     */
    public void setValues() {
        return;
    }
    /**
     * Makes the component visible
     */
    public void show() {
        return;
    }
    /**
     * Makes visible those elements which parameter 'batch' is set to the specified name
     */
    public void showBatch() {
        return;
    }
    /**
     * Breaks "bind" link
     */
    public void unbind() {
        return;
    }
    /**
     * Cancels blocking events that was enabled by the 'blockEvent' command
     */
    public void unblockEvent() {
        return;
    }
    /**
     * Checks data in the component during adding new item or editing existing ones
     */
    public Boolean validate() {
        return null;
    }
}
