// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.3,
// any modifications will be overwritten.
// ==============================================================

package com.webix.ui.model.layouts;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import com.webix.ui.model.AnimateConfig;
import com.webix.ui.model.Baselayout;
import com.webix.ui.model.Baseview;
import com.webix.ui.model.DelimiterConfig;
import com.webix.ui.model.EventHandler;
import com.webix.ui.model.EventHandlerList;
import com.webix.ui.model.GraphItemConfig;
import com.webix.ui.model.NavigationConfig;
import com.webix.ui.model.PaddingConfig;
import com.webix.ui.model.Proto;
import com.webix.ui.model.RGBColorList;
import com.webix.ui.model.TypeConfig;
import com.webix.ui.model.UnknownType;
import com.webix.ui.model.View;
import com.webix.ui.model.auxiliary.Calendar;
import com.webix.ui.model.auxiliary.Colorboard;
import com.webix.ui.model.auxiliary.Pager;
import com.webix.ui.model.auxiliary.Resizer;
import com.webix.ui.model.auxiliary.Spacer;
import com.webix.ui.model.auxiliary.Tooltip;
import com.webix.ui.model.auxiliary.Video;
import com.webix.ui.model.context.Context;
import com.webix.ui.model.context.Contextmenu;
import com.webix.ui.model.context.Datasuggest;
import com.webix.ui.model.context.Gridsuggest;
import com.webix.ui.model.context.Menu;
import com.webix.ui.model.context.Popup;
import com.webix.ui.model.context.Submenu;
import com.webix.ui.model.context.Suggest;
import com.webix.ui.model.context.Window;
import com.webix.ui.model.data.Chart;
import com.webix.ui.model.data.Datatable;
import com.webix.ui.model.data.Dataview;
import com.webix.ui.model.data.Grouplist;
import com.webix.ui.model.data.List;
import com.webix.ui.model.data.Property;
import com.webix.ui.model.data.Tree;
import com.webix.ui.model.data.Treetable;
import com.webix.ui.model.data.Unitlist;
import com.webix.ui.model.form.Button;
import com.webix.ui.model.form.Checkbox;
import com.webix.ui.model.form.Colorpicker;
import com.webix.ui.model.form.Combo;
import com.webix.ui.model.form.Counter;
import com.webix.ui.model.form.Datepicker;
import com.webix.ui.model.form.Fieldset;
import com.webix.ui.model.form.Icon;
import com.webix.ui.model.form.Label;
import com.webix.ui.model.form.Multiselect;
import com.webix.ui.model.form.Multitext;
import com.webix.ui.model.form.Radio;
import com.webix.ui.model.form.Richselect;
import com.webix.ui.model.form.Search;
import com.webix.ui.model.form.Segmented;
import com.webix.ui.model.form.Select;
import com.webix.ui.model.form.Slider;
import com.webix.ui.model.form.Tabbar;
import com.webix.ui.model.form.Text;
import com.webix.ui.model.form.Textarea;
import com.webix.ui.model.form.Toggle;
import com.webix.ui.model.html.Htmlform;
import com.webix.ui.model.html.Iframe;
import com.webix.ui.model.html.Scrollview;
import com.webix.ui.model.html.Template;





/**
 * 
 * A horizontal toolbar.
 * The component can contain various elements inside it (actually,
 * the same elements that the form can contain): an icon, a button,
 * a label, an input box etc. Check <a
 * href="http://docs.webix.com/desktop__toolbar.html">toolbar</a>
 * documentation for more detailed description.
 * 
 * 
 * @version $Revision$ $Date$
 */
@com.webix.ui.model.WebixEvent({
    com.webix.ui.model.Event.ON_AFTER_LOAD,
    com.webix.ui.model.Event.ON_AFTER_VALIDATION,
    com.webix.ui.model.Event.ON_BEFORE_LOAD,
    com.webix.ui.model.Event.ON_BEFORE_VALIDATE,
    com.webix.ui.model.Event.ON_BIND_REQUEST,
    com.webix.ui.model.Event.ON_CHANGE,
    com.webix.ui.model.Event.ON_DESTRUCT,
    com.webix.ui.model.Event.ON_LOAD_ERROR,
    com.webix.ui.model.Event.ON_VALIDATION_ERROR,
    com.webix.ui.model.Event.ON_VALIDATION_SUCCESS
})
@com.webix.ui.model.WebixName("toolbar")
@javax.xml.bind.annotation.XmlRootElement
public class Toolbar
    extends Baselayout
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field elements.
     */
    @com.webix.ui.model.WebixType("array")
    private java.util.List<View> elements;

    /**
     * Settings, which will be applied to all nested inputs<br
     * /><br /><a
     * href="http://docs.webix.com/api__ui.toolbar_elementsconfig_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("hash")
    private java.util.Map<String, String> elementsConfig;

    /**
     * Masks IDs of all inner element<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_isolate_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("boolean")
    private Boolean isolate;

    /**
     * Defines the space around elements (applies the specified
     * value to all elements)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_margin_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer margin;

    /**
     * Defines the space between the element borders and content
     * (applies the specified value to all sides).<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_padding_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer padding;

    /**
     * Sets the right and left padding (applies the specified value
     * to both sides)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_paddingx_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer paddingX;

    /**
     * Sets the top and bottom padding (applies the specified value
     * to both sides)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_paddingy_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer paddingY;

    /**
     * Defines a set of rules for input field(s) of the
     * form(htmlform)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_rules_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("")
    private java.util.Map<String, String> rules;

    /**
     * Enables/disables the scroll bar<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_scroll_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool|string")
    private String scroll;

    /**
     * The time during which the component is scrolled to the
     * specified position (in milliseconds)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_scrollspeed_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string")
    private String scrollSpeed;

    /**
     * Defines the layout borders<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_type_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string")
    private String type;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method getElements.
     * 
     * @return List
     */
    public java.util.List<View> getElements()
    {
        if ( this.elements == null )
        {
            this.elements = new java.util.ArrayList<View>();
        }

        return this.elements;
    } //-- java.util.List<View> getElements()

    /**
     * Get settings, which will be applied to all nested inputs<br
     * /><br /><a
     * href="http://docs.webix.com/api__ui.toolbar_elementsconfig_config.html">Webix
     * API Reference</a>
     * 
     * @return java.util.Map<String, String>
     */
    public java.util.Map<String, String> getElementsConfig()
    {
        return this.elementsConfig;
    } //-- java.util.Map<String, String> getElementsConfig()

    /**
     * Get defines the space around elements (applies the specified
     * value to all elements)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_margin_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getMargin()
    {
        return this.margin;
    } //-- Integer getMargin()

    /**
     * Get defines the space between the element borders and
     * content (applies the specified value to all sides).<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_padding_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getPadding()
    {
        return this.padding;
    } //-- Integer getPadding()

    /**
     * Get sets the right and left padding (applies the specified
     * value to both sides)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_paddingx_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getPaddingX()
    {
        return this.paddingX;
    } //-- Integer getPaddingX()

    /**
     * Get sets the top and bottom padding (applies the specified
     * value to both sides)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_paddingy_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getPaddingY()
    {
        return this.paddingY;
    } //-- Integer getPaddingY()

    /**
     * Get defines a set of rules for input field(s) of the
     * form(htmlform)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_rules_config.html">Webix
     * API Reference</a>
     * 
     * @return java.util.Map<String, String>
     */
    public java.util.Map<String, String> getRules()
    {
        return this.rules;
    } //-- java.util.Map<String, String> getRules()

    /**
     * Get enables/disables the scroll bar<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_scroll_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getScroll()
    {
        return this.scroll;
    } //-- String getScroll()

    /**
     * Get the time during which the component is scrolled to the
     * specified position (in milliseconds)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_scrollspeed_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getScrollSpeed()
    {
        return this.scrollSpeed;
    } //-- String getScrollSpeed()

    /**
     * Get defines the layout borders<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_type_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getType()
    {
        return this.type;
    } //-- String getType()

    /**
     * Get masks IDs of all inner element<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_isolate_config.html">Webix
     * API Reference</a>
     * 
     * @return Boolean
     */
    public Boolean isIsolate()
    {
        return this.isolate;
    } //-- Boolean isIsolate()

    /**
     * Set collection of subviews<br /><br /><a
     * href="http://docs.webix.com/api__ui.toolbar_elements_config.html">Webix
     * API Reference</a>
     * 
     * @param elements
     */
    public void setElements( java.util.List<View> elements )
    {
        this.elements = elements;
    } //-- void setElements( java.util.List )

    /**
     * Set settings, which will be applied to all nested inputs<br
     * /><br /><a
     * href="http://docs.webix.com/api__ui.toolbar_elementsconfig_config.html">Webix
     * API Reference</a>
     * 
     * @param elementsConfig
     */
    public void setElementsConfig( java.util.Map<String, String> elementsConfig )
    {
        this.elementsConfig = elementsConfig;
    } //-- void setElementsConfig( java.util.Map<String, String> )

    /**
     * Set masks IDs of all inner element<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_isolate_config.html">Webix
     * API Reference</a>
     * 
     * @param isolate
     */
    public void setIsolate( Boolean isolate )
    {
        this.isolate = isolate;
    } //-- void setIsolate( Boolean )

    /**
     * Set defines the space around elements (applies the specified
     * value to all elements)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_margin_config.html">Webix
     * API Reference</a>
     * 
     * @param margin
     */
    public void setMargin( Integer margin )
    {
        this.margin = margin;
    } //-- void setMargin( Integer )

    /**
     * Set defines the space between the element borders and
     * content (applies the specified value to all sides).<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_padding_config.html">Webix
     * API Reference</a>
     * 
     * @param padding
     */
    public void setPadding( Integer padding )
    {
        this.padding = padding;
    } //-- void setPadding( Integer )

    /**
     * Set sets the right and left padding (applies the specified
     * value to both sides)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_paddingx_config.html">Webix
     * API Reference</a>
     * 
     * @param paddingX
     */
    public void setPaddingX( Integer paddingX )
    {
        this.paddingX = paddingX;
    } //-- void setPaddingX( Integer )

    /**
     * Set sets the top and bottom padding (applies the specified
     * value to both sides)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_paddingy_config.html">Webix
     * API Reference</a>
     * 
     * @param paddingY
     */
    public void setPaddingY( Integer paddingY )
    {
        this.paddingY = paddingY;
    } //-- void setPaddingY( Integer )

    /**
     * Set defines a set of rules for input field(s) of the
     * form(htmlform)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_rules_config.html">Webix
     * API Reference</a>
     * 
     * @param rules
     */
    public void setRules( java.util.Map<String, String> rules )
    {
        this.rules = rules;
    } //-- void setRules( java.util.Map<String, String> )

    /**
     * Set enables/disables the scroll bar<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_scroll_config.html">Webix
     * API Reference</a>
     * 
     * @param scroll
     */
    public void setScroll( String scroll )
    {
        this.scroll = scroll;
    } //-- void setScroll( String )

    /**
     * Set the time during which the component is scrolled to the
     * specified position (in milliseconds)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_scrollspeed_config.html">Webix
     * API Reference</a>
     * 
     * @param scrollSpeed
     */
    public void setScrollSpeed( String scrollSpeed )
    {
        this.scrollSpeed = scrollSpeed;
    } //-- void setScrollSpeed( String )

    /**
     * Set defines the layout borders<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.toolbar_type_config.html">Webix
     * API Reference</a>
     * 
     * @param type
     */
    public void setType( String type )
    {
        this.type = type;
    } //-- void setType( String )

}
