// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.3,
// any modifications will be overwritten.
// ==============================================================

package com.webix.ui.model.data;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import com.webix.ui.model.AnimateConfig;
import com.webix.ui.model.Baselayout;
import com.webix.ui.model.Baseview;
import com.webix.ui.model.DelimiterConfig;
import com.webix.ui.model.EventHandler;
import com.webix.ui.model.EventHandlerList;
import com.webix.ui.model.GraphItemConfig;
import com.webix.ui.model.NavigationConfig;
import com.webix.ui.model.PaddingConfig;
import com.webix.ui.model.Proto;
import com.webix.ui.model.RGBColorList;
import com.webix.ui.model.TypeConfig;
import com.webix.ui.model.UnknownType;
import com.webix.ui.model.View;
import com.webix.ui.model.auxiliary.Calendar;
import com.webix.ui.model.auxiliary.Colorboard;
import com.webix.ui.model.auxiliary.Pager;
import com.webix.ui.model.auxiliary.Resizer;
import com.webix.ui.model.auxiliary.Spacer;
import com.webix.ui.model.auxiliary.Tooltip;
import com.webix.ui.model.auxiliary.Video;
import com.webix.ui.model.context.Context;
import com.webix.ui.model.context.Contextmenu;
import com.webix.ui.model.context.Datasuggest;
import com.webix.ui.model.context.Gridsuggest;
import com.webix.ui.model.context.Menu;
import com.webix.ui.model.context.Popup;
import com.webix.ui.model.context.Submenu;
import com.webix.ui.model.context.Suggest;
import com.webix.ui.model.context.Window;
import com.webix.ui.model.form.Button;
import com.webix.ui.model.form.Checkbox;
import com.webix.ui.model.form.Colorpicker;
import com.webix.ui.model.form.Combo;
import com.webix.ui.model.form.Counter;
import com.webix.ui.model.form.Datepicker;
import com.webix.ui.model.form.Fieldset;
import com.webix.ui.model.form.Icon;
import com.webix.ui.model.form.Label;
import com.webix.ui.model.form.Multiselect;
import com.webix.ui.model.form.Multitext;
import com.webix.ui.model.form.Radio;
import com.webix.ui.model.form.Richselect;
import com.webix.ui.model.form.Search;
import com.webix.ui.model.form.Segmented;
import com.webix.ui.model.form.Select;
import com.webix.ui.model.form.Slider;
import com.webix.ui.model.form.Tabbar;
import com.webix.ui.model.form.Text;
import com.webix.ui.model.form.Textarea;
import com.webix.ui.model.form.Toggle;
import com.webix.ui.model.html.Htmlform;
import com.webix.ui.model.html.Iframe;
import com.webix.ui.model.html.Scrollview;
import com.webix.ui.model.html.Template;
import com.webix.ui.model.layouts.Accordion;
import com.webix.ui.model.layouts.Accordionitem;
import com.webix.ui.model.layouts.Carousel;
import com.webix.ui.model.layouts.Form;
import com.webix.ui.model.layouts.Headerlayout;
import com.webix.ui.model.layouts.Layout;
import com.webix.ui.model.layouts.Multiview;
import com.webix.ui.model.layouts.Tabview;
import com.webix.ui.model.layouts.Toolbar;





/**
 * 
 * A control for displaying data in a tabular format.
 * The component presents a collection of objects according to a
 * user-defined template. Support for various template forms and
 * the possibility to sort, filter data. Check <a
 * href="http://docs.webix.com/desktop__dataview.html">dataview</a>
 * documentation for more detailed description.
 * 
 * 
 * @version $Revision$ $Date$
 */
@com.webix.ui.model.WebixEvent({
    com.webix.ui.model.Event.ON_AFTER_ADD,
    com.webix.ui.model.Event.ON_AFTER_CONTEXT_MENU,
    com.webix.ui.model.Event.ON_AFTER_DELETE,
    com.webix.ui.model.Event.ON_AFTER_DROP,
    com.webix.ui.model.Event.ON_AFTER_LOAD,
    com.webix.ui.model.Event.ON_AFTER_RENDER,
    com.webix.ui.model.Event.ON_AFTER_SCROLL,
    com.webix.ui.model.Event.ON_AFTER_SELECT,
    com.webix.ui.model.Event.ON_AFTER_SORT,
    com.webix.ui.model.Event.ON_BEFORE_ADD,
    com.webix.ui.model.Event.ON_BEFORE_CONTEXT_MENU,
    com.webix.ui.model.Event.ON_BEFORE_DELETE,
    com.webix.ui.model.Event.ON_BEFORE_DRAG,
    com.webix.ui.model.Event.ON_BEFORE_DRAG_IN,
    com.webix.ui.model.Event.ON_BEFORE_DROP,
    com.webix.ui.model.Event.ON_BEFORE_DROP_OUT,
    com.webix.ui.model.Event.ON_BEFORE_LOAD,
    com.webix.ui.model.Event.ON_BEFORE_RENDER,
    com.webix.ui.model.Event.ON_BEFORE_SELECT,
    com.webix.ui.model.Event.ON_BEFORE_SORT,
    com.webix.ui.model.Event.ON_BIND_REQUEST,
    com.webix.ui.model.Event.ON_DATA_REQUEST,
    com.webix.ui.model.Event.ON_DATA_UPDATE,
    com.webix.ui.model.Event.ON_DESTRUCT,
    com.webix.ui.model.Event.ON_DRAG_OUT,
    com.webix.ui.model.Event.ON_ITEM_CLICK,
    com.webix.ui.model.Event.ON_ITEM_DBL_CLICK,
    com.webix.ui.model.Event.ON_ITEM_RENDER,
    com.webix.ui.model.Event.ON_KEY_PRESS,
    com.webix.ui.model.Event.ON_LOAD_ERROR,
    com.webix.ui.model.Event.ON_LONG_TOUCH,
    com.webix.ui.model.Event.ON_MOUSE_MOVE,
    com.webix.ui.model.Event.ON_MOUSE_MOVING,
    com.webix.ui.model.Event.ON_MOUSE_OUT,
    com.webix.ui.model.Event.ON_SELECT_CHANGE,
    com.webix.ui.model.Event.ON_SWIPE_X,
    com.webix.ui.model.Event.ON_SWIPE_Y,
    com.webix.ui.model.Event.ON_TIMED_KEY_PRESS,
    com.webix.ui.model.Event.ON_TOUCH_END,
    com.webix.ui.model.Event.ON_TOUCH_MOVE,
    com.webix.ui.model.Event.ON_TOUCH_START,
    com.webix.ui.model.Event.ON_VALIDATION_ERROR,
    com.webix.ui.model.Event.ON_VALIDATION_SUCCESS,
    com.webix.ui.model.Event.ON_VIEW_RESIZE
})
@com.webix.ui.model.WebixName("dataview")
@javax.xml.bind.annotation.XmlRootElement
public class Dataview
    extends View
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Enables autosizing to content<br /><br /><a
     * href="http://docs.webix.com/api__ui.dataview_autoheight_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool")
    private Boolean autoheight;

    /**
     * Defines the start position DataTable will load data from<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_datafetch_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer datafetch;

    /**
     * Enables or disables drag-and-drop<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_drag_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool|string")
    private String drag;

    /**
     * Enables autoscroll of component during drag-n-drop<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.dataview_dragscroll_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool|string")
    private String dragscroll;

    /**
     * Allows defining custom 'move' logic for the component.<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_externaldata_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("function")
    private String externalData;

    /**
     * How much records need to be preloaded in additional to
     * mandatory ones<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_loadahead_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer loadahead;

    /**
     * The delay between a real mouse action and invoking the
     * related events<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_mouseeventdelay_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer mouseEventDelay;

    /**
     * Activates the selection keyboard navigation<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_navigation_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool")
    private Boolean navigation;

    /**
     * Attaches a click behavior for component items with the
     * specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_onclick_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("hash")
    private java.util.Map<String, String> onClick;

    /**
     * A property used to define custom context-click (right click)
     * handlers for elements in the DataTable cells<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_oncontext_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("hash")
    private java.util.Map<String, String> onContext;

    /**
     * Attaches a dblclick behavior for component items with the
     * specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_ondblclick_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("function")
    private java.util.Map<String, String> onDblClick;

    /**
     * Attaches a mousemove behaviour for component items with the
     * specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_onmousemove_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("function")
    private java.util.Map<String, String> onMouseMove;

    /**
     * Enables/disables the scroll bar<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_scroll_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool|string")
    private String scroll;

    /**
     * The time during which the component is scrolled to the
     * specified position (in milliseconds)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_scrollspeed_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("string")
    private String scrollSpeed;

    /**
     * Enables/disables item selection or multiselection in
     * grouplist<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_select_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("bool|string")
    private String select;

    /**
     * Adjusts the view width to display the defined number of
     * items in a row<br /><br /><a
     * href="http://docs.webix.com/api__ui.dataview_xcount_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer xCount;

    /**
     * Adjusts the view height to display the defined number of
     * items in a column<br /><br /><a
     * href="http://docs.webix.com/api__ui.dataview_ycount_config.html">Webix
     * API Reference</a>
     */
    @com.webix.ui.model.WebixType("number")
    private Integer yCount;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get defines the start position DataTable will load data
     * from<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_datafetch_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getDatafetch()
    {
        return this.datafetch;
    } //-- Integer getDatafetch()

    /**
     * Get enables or disables drag-and-drop<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_drag_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getDrag()
    {
        return this.drag;
    } //-- String getDrag()

    /**
     * Get enables autoscroll of component during drag-n-drop<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_dragscroll_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getDragscroll()
    {
        return this.dragscroll;
    } //-- String getDragscroll()

    /**
     * Get allows defining custom 'move' logic for the
     * component.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_externaldata_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getExternalData()
    {
        return this.externalData;
    } //-- String getExternalData()

    /**
     * Get how much records need to be preloaded in additional to
     * mandatory ones<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_loadahead_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getLoadahead()
    {
        return this.loadahead;
    } //-- Integer getLoadahead()

    /**
     * Get the delay between a real mouse action and invoking the
     * related events<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_mouseeventdelay_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getMouseEventDelay()
    {
        return this.mouseEventDelay;
    } //-- Integer getMouseEventDelay()

    /**
     * Get attaches a click behavior for component items with the
     * specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_onclick_config.html">Webix
     * API Reference</a>
     * 
     * @return java.util.Map<String, String>
     */
    public java.util.Map<String, String> getOnClick()
    {
        return this.onClick;
    } //-- java.util.Map<String, String> getOnClick()

    /**
     * Get a property used to define custom context-click (right
     * click) handlers for elements in the DataTable cells<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.dataview_oncontext_config.html">Webix
     * API Reference</a>
     * 
     * @return java.util.Map<String, String>
     */
    public java.util.Map<String, String> getOnContext()
    {
        return this.onContext;
    } //-- java.util.Map<String, String> getOnContext()

    /**
     * Get attaches a dblclick behavior for component items with
     * the specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_ondblclick_config.html">Webix
     * API Reference</a>
     * 
     * @return java.util.Map<String, String>
     */
    public java.util.Map<String, String> getOnDblClick()
    {
        return this.onDblClick;
    } //-- java.util.Map<String, String> getOnDblClick()

    /**
     * Get attaches a mousemove behaviour for component items with
     * the specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_onmousemove_config.html">Webix
     * API Reference</a>
     * 
     * @return java.util.Map<String, String>
     */
    public java.util.Map<String, String> getOnMouseMove()
    {
        return this.onMouseMove;
    } //-- java.util.Map<String, String> getOnMouseMove()

    /**
     * Get enables/disables the scroll bar<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_scroll_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getScroll()
    {
        return this.scroll;
    } //-- String getScroll()

    /**
     * Get the time during which the component is scrolled to the
     * specified position (in milliseconds)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_scrollspeed_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getScrollSpeed()
    {
        return this.scrollSpeed;
    } //-- String getScrollSpeed()

    /**
     * Get enables/disables item selection or multiselection in
     * grouplist<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_select_config.html">Webix
     * API Reference</a>
     * 
     * @return String
     */
    public String getSelect()
    {
        return this.select;
    } //-- String getSelect()

    /**
     * Get adjusts the view width to display the defined number of
     * items in a row<br /><br /><a
     * href="http://docs.webix.com/api__ui.dataview_xcount_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getXCount()
    {
        return this.xCount;
    } //-- Integer getXCount()

    /**
     * Get adjusts the view height to display the defined number of
     * items in a column<br /><br /><a
     * href="http://docs.webix.com/api__ui.dataview_ycount_config.html">Webix
     * API Reference</a>
     * 
     * @return Integer
     */
    public Integer getYCount()
    {
        return this.yCount;
    } //-- Integer getYCount()

    /**
     * Get enables autosizing to content<br /><br /><a
     * href="http://docs.webix.com/api__ui.dataview_autoheight_config.html">Webix
     * API Reference</a>
     * 
     * @return Boolean
     */
    public Boolean isAutoheight()
    {
        return this.autoheight;
    } //-- Boolean isAutoheight()

    /**
     * Get activates the selection keyboard navigation<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.dataview_navigation_config.html">Webix
     * API Reference</a>
     * 
     * @return Boolean
     */
    public Boolean isNavigation()
    {
        return this.navigation;
    } //-- Boolean isNavigation()

    /**
     * Set enables autosizing to content<br /><br /><a
     * href="http://docs.webix.com/api__ui.dataview_autoheight_config.html">Webix
     * API Reference</a>
     * 
     * @param autoheight
     */
    public void setAutoheight( Boolean autoheight )
    {
        this.autoheight = autoheight;
    } //-- void setAutoheight( Boolean )

    /**
     * Set defines the start position DataTable will load data
     * from<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_datafetch_config.html">Webix
     * API Reference</a>
     * 
     * @param datafetch
     */
    public void setDatafetch( Integer datafetch )
    {
        this.datafetch = datafetch;
    } //-- void setDatafetch( Integer )

    /**
     * Set enables or disables drag-and-drop<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_drag_config.html">Webix
     * API Reference</a>
     * 
     * @param drag
     */
    public void setDrag( String drag )
    {
        this.drag = drag;
    } //-- void setDrag( String )

    /**
     * Set enables autoscroll of component during drag-n-drop<br
     * /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_dragscroll_config.html">Webix
     * API Reference</a>
     * 
     * @param dragscroll
     */
    public void setDragscroll( String dragscroll )
    {
        this.dragscroll = dragscroll;
    } //-- void setDragscroll( String )

    /**
     * Set allows defining custom 'move' logic for the
     * component.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_externaldata_config.html">Webix
     * API Reference</a>
     * 
     * @param externalData
     */
    public void setExternalData( String externalData )
    {
        this.externalData = externalData;
    } //-- void setExternalData( String )

    /**
     * Set how much records need to be preloaded in additional to
     * mandatory ones<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_loadahead_config.html">Webix
     * API Reference</a>
     * 
     * @param loadahead
     */
    public void setLoadahead( Integer loadahead )
    {
        this.loadahead = loadahead;
    } //-- void setLoadahead( Integer )

    /**
     * Set the delay between a real mouse action and invoking the
     * related events<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_mouseeventdelay_config.html">Webix
     * API Reference</a>
     * 
     * @param mouseEventDelay
     */
    public void setMouseEventDelay( Integer mouseEventDelay )
    {
        this.mouseEventDelay = mouseEventDelay;
    } //-- void setMouseEventDelay( Integer )

    /**
     * Set activates the selection keyboard navigation<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.dataview_navigation_config.html">Webix
     * API Reference</a>
     * 
     * @param navigation
     */
    public void setNavigation( Boolean navigation )
    {
        this.navigation = navigation;
    } //-- void setNavigation( Boolean )

    /**
     * Set attaches a click behavior for component items with the
     * specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_onclick_config.html">Webix
     * API Reference</a>
     * 
     * @param onClick
     */
    public void setOnClick( java.util.Map<String, String> onClick )
    {
        this.onClick = onClick;
    } //-- void setOnClick( java.util.Map<String, String> )

    /**
     * Set a property used to define custom context-click (right
     * click) handlers for elements in the DataTable cells<br /><br
     * /><a
     * href="http://docs.webix.com/api__link__ui.dataview_oncontext_config.html">Webix
     * API Reference</a>
     * 
     * @param onContext
     */
    public void setOnContext( java.util.Map<String, String> onContext )
    {
        this.onContext = onContext;
    } //-- void setOnContext( java.util.Map<String, String> )

    /**
     * Set attaches a dblclick behavior for component items with
     * the specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_ondblclick_config.html">Webix
     * API Reference</a>
     * 
     * @param onDblClick
     */
    public void setOnDblClick( java.util.Map<String, String> onDblClick )
    {
        this.onDblClick = onDblClick;
    } //-- void setOnDblClick( java.util.Map<String, String> )

    /**
     * Set attaches a mousemove behaviour for component items with
     * the specified CSS class.<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_onmousemove_config.html">Webix
     * API Reference</a>
     * 
     * @param onMouseMove
     */
    public void setOnMouseMove( java.util.Map<String, String> onMouseMove )
    {
        this.onMouseMove = onMouseMove;
    } //-- void setOnMouseMove( java.util.Map<String, String> )

    /**
     * Set enables/disables the scroll bar<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_scroll_config.html">Webix
     * API Reference</a>
     * 
     * @param scroll
     */
    public void setScroll( String scroll )
    {
        this.scroll = scroll;
    } //-- void setScroll( String )

    /**
     * Set the time during which the component is scrolled to the
     * specified position (in milliseconds)<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_scrollspeed_config.html">Webix
     * API Reference</a>
     * 
     * @param scrollSpeed
     */
    public void setScrollSpeed( String scrollSpeed )
    {
        this.scrollSpeed = scrollSpeed;
    } //-- void setScrollSpeed( String )

    /**
     * Set enables/disables item selection or multiselection in
     * grouplist<br /><br /><a
     * href="http://docs.webix.com/api__link__ui.dataview_select_config.html">Webix
     * API Reference</a>
     * 
     * @param select
     */
    public void setSelect( String select )
    {
        this.select = select;
    } //-- void setSelect( String )

    /**
     * Set adjusts the view width to display the defined number of
     * items in a row<br /><br /><a
     * href="http://docs.webix.com/api__ui.dataview_xcount_config.html">Webix
     * API Reference</a>
     * 
     * @param xCount
     */
    public void setXCount( Integer xCount )
    {
        this.xCount = xCount;
    } //-- void setXCount( Integer )

    /**
     * Set adjusts the view height to display the defined number of
     * items in a column<br /><br /><a
     * href="http://docs.webix.com/api__ui.dataview_ycount_config.html">Webix
     * API Reference</a>
     * 
     * @param yCount
     */
    public void setYCount( Integer yCount )
    {
        this.yCount = yCount;
    } //-- void setYCount( Integer )

}
