// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package com.webix.ui.model.data;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import com.webix.ui.model.auxiliary.Calendar;
import com.webix.ui.model.auxiliary.Colorboard;
import com.webix.ui.model.auxiliary.Pager;
import com.webix.ui.model.auxiliary.Resizer;
import com.webix.ui.model.auxiliary.Spacer;
import com.webix.ui.model.auxiliary.Tooltip;
import com.webix.ui.model.auxiliary.Video;
import com.webix.ui.model.context.Context;
import com.webix.ui.model.context.Contextmenu;
import com.webix.ui.model.context.Datasuggest;
import com.webix.ui.model.context.Gridsuggest;
import com.webix.ui.model.context.Menu;
import com.webix.ui.model.context.Popup;
import com.webix.ui.model.context.Submenu;
import com.webix.ui.model.context.Suggest;
import com.webix.ui.model.context.Window;
import com.webix.ui.model.form.Button;
import com.webix.ui.model.form.Checkbox;
import com.webix.ui.model.form.Colorpicker;
import com.webix.ui.model.form.Combo;
import com.webix.ui.model.form.Counter;
import com.webix.ui.model.form.Datepicker;
import com.webix.ui.model.form.Fieldset;
import com.webix.ui.model.form.Icon;
import com.webix.ui.model.form.Label;
import com.webix.ui.model.form.Multiselect;
import com.webix.ui.model.form.Multitext;
import com.webix.ui.model.form.Radio;
import com.webix.ui.model.form.Richselect;
import com.webix.ui.model.form.Search;
import com.webix.ui.model.form.Segmented;
import com.webix.ui.model.form.Select;
import com.webix.ui.model.form.Slider;
import com.webix.ui.model.form.Tabbar;
import com.webix.ui.model.form.Text;
import com.webix.ui.model.form.Textarea;
import com.webix.ui.model.form.Toggle;
import com.webix.ui.model.html.Htmlform;
import com.webix.ui.model.html.Iframe;
import com.webix.ui.model.html.Scrollview;
import com.webix.ui.model.html.Template;
import com.webix.ui.model.layouts.Accordion;
import com.webix.ui.model.layouts.Accordionitem;
import com.webix.ui.model.layouts.Carousel;
import com.webix.ui.model.layouts.Form;
import com.webix.ui.model.layouts.Headerlayout;
import com.webix.ui.model.layouts.Layout;
import com.webix.ui.model.layouts.Multiview;
import com.webix.ui.model.layouts.Tabview;
import com.webix.ui.model.layouts.Toolbar;

/**
 * A vertical list of items grouped into sections by some
 * category.The component provides navigation within the list and
 * between the sections. Support for various data template formats,
 * sorting and filtering features. Check grouplist documentation
 * for more detailed description.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Grouplist
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Defines or disables view change animation.
     */
    private Byte animate;

    /**
     * Height of view will be adjusted to show all items.
     */
    private Byte autoheight;

    /**
     * Width of view will be adjusted to show all items.
     */
    private Byte autowidth;

    /**
     * Used to hide the component borders.
     */
    private Byte borderless;

    /**
     * Sets an action happening on a button click.
     */
    private Byte click;

    /**
     * Enables/disables clipboard support.
     */
    private Byte clipboard;

    /**
     * An html container (or its id) where the component needs
     * initializing.
     */
    private Byte container;

    /**
     * The name of a css class that will be applied to the view
     * container.
     */
    private Byte css;

    /**
     * An inline dataset that data to the component will be load
     * from.
     */
    private Byte data;

    /**
     * The url to the data source that the component will use to
     * reload data from.
     */
    private Byte dataFeed;

    /**
     * Sets the polling interval (the time period between the
     * completion of a network request and the next request for
     * data).
     */
    private Byte datathrottle;

    /**
     * The type of loaded data.
     */
    private Byte datatype;

    /**
     * Disables item.
     */
    private Byte disabled;

    /**
     * Enables or disables drag-and-drop.
     */
    private Byte drag;

    /**
     * Enables autoscroll of component during drag-n-drop.
     */
    private Byte dragscroll;

    /**
     * Allows defining custom 'move' logic for the component.
     */
    private Byte externalData;

    /**
     * Sets the view gravity (1 by default).
     */
    private Byte gravity;

    /**
     * Sets the height of the component.
     */
    private Byte height;

    /**
     * Defines whether the view will be hidden initially.
     */
    private Byte hidden;

    /**
     * The component ID.
     */
    private Byte id;

    /**
     * Defines x or y orientation of layout.
     */
    private Byte layout;

    /**
     * Sets the maximum height for the view.
     */
    private Byte maxHeight;

    /**
     * Sets the maximum width for the view.
     */
    private Byte maxWidth;

    /**
     * Sets the minimal height for the view.
     */
    private Byte minHeight;

    /**
     * Sets the minimal width for the view.
     */
    private Byte minWidth;

    /**
     * The delay between a real mouse action and invoking the
     * related events.
     */
    private Byte mouseEventDelay;

    /**
     * Activates the selection keyboard navigation.
     */
    private Byte navigation;

    /**
     * Allows attaching custom handlers to inner events of the
     * component.
     */
    private Byte on;

    /**
     * Attaches a click behavior for component items with the
     * specified CSS class.
     */
    private Byte onClick;

    /**
     * A property used to define custom context-click (right click)
     * handlers for elements in the DataTable cells
     * .
     */
    private Byte onContext;

    /**
     * Attaches a dblclick behavior for component items with the
     * specified CSS class.
     */
    private Byte onDblClick;

    /**
     * Attaches a dblclick behavior for component items with the
     * specified CSS class.
     */
    private Byte onMouseMove;

    /**
     * Defines paging configuration ( creates a 'ui.pager' object).
     */
    private Byte pager;

    /**
     * A handler that is called just after the page has been
     * completely parsed.
     */
    private Byte ready;

    /**
     * Defines how to treat items in case of reloading.
     */
    private Byte removeMissed;

    /**
     * Set of validation rules for the component.
     */
    private Byte rules;

    /**
     * Defines urls for datasaving.
     */
    private Byte save;

    /**
     * Defines schemes for data processing.
     */
    private Byte scheme;

    /**
     * Enables/disables the scroll bar.
     */
    private Byte scroll;

    /**
     * The time during which the component is scrolled to the
     * specified position (in milliseconds).
     */
    private Byte scrollSpeed;

    /**
     * Enables/disables item selection or multiselection in
     * grouplist.
     */
    private Byte select;

    /**
     * The component template.
     */
    private Byte template;

    /**
     * An html template that defines data that will be presented in
     * group header in the expanded state.
     */
    private Byte templateBack;

    /**
     * Sets the template according to which data will be copied to
     * the clipboard.
     */
    private Byte templateCopy;

    /**
     * An html template that defines data that will be presented in
     * group header in the collapsed state.
     */
    private Byte templateGroup;

    /**
     * An html template that defines data that will be presented in
     * grouplist.
     */
    private Byte templateItem;

    /**
     * Sets a popup message appearing on pointing a mouse cursor
     * over the dedicated item.
     */
    private Byte tooltip;

    /**
     * Object that specifies items presentation.
     */
    private Byte type;

    /**
     * The url of a data feed which will be loaded after component
     * initialization.
     */
    private Byte url;

    /**
     * Sets the width of the component.
     */
    private Byte width;

    /**
     * Defines width of view in items.
     */
    private Byte xCount;

    /**
     * Defines height of view in items.
     */
    private Byte yCount;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get defines or disables view change animation.
     * 
     * @return Byte
     */
    public Byte getAnimate()
    {
        return this.animate;
    } //-- Byte getAnimate()

    /**
     * Get height of view will be adjusted to show all items.
     * 
     * @return Byte
     */
    public Byte getAutoheight()
    {
        return this.autoheight;
    } //-- Byte getAutoheight()

    /**
     * Get width of view will be adjusted to show all items.
     * 
     * @return Byte
     */
    public Byte getAutowidth()
    {
        return this.autowidth;
    } //-- Byte getAutowidth()

    /**
     * Get used to hide the component borders.
     * 
     * @return Byte
     */
    public Byte getBorderless()
    {
        return this.borderless;
    } //-- Byte getBorderless()

    /**
     * Get sets an action happening on a button click.
     * 
     * @return Byte
     */
    public Byte getClick()
    {
        return this.click;
    } //-- Byte getClick()

    /**
     * Get enables/disables clipboard support.
     * 
     * @return Byte
     */
    public Byte getClipboard()
    {
        return this.clipboard;
    } //-- Byte getClipboard()

    /**
     * Get an html container (or its id) where the component needs
     * initializing.
     * 
     * @return Byte
     */
    public Byte getContainer()
    {
        return this.container;
    } //-- Byte getContainer()

    /**
     * Get the name of a css class that will be applied to the view
     * container.
     * 
     * @return Byte
     */
    public Byte getCss()
    {
        return this.css;
    } //-- Byte getCss()

    /**
     * Get an inline dataset that data to the component will be
     * load from.
     * 
     * @return Byte
     */
    public Byte getData()
    {
        return this.data;
    } //-- Byte getData()

    /**
     * Get the url to the data source that the component will use
     * to reload data from.
     * 
     * @return Byte
     */
    public Byte getDataFeed()
    {
        return this.dataFeed;
    } //-- Byte getDataFeed()

    /**
     * Get sets the polling interval (the time period between the
     * completion of a network request and the next request for
     * data).
     * 
     * @return Byte
     */
    public Byte getDatathrottle()
    {
        return this.datathrottle;
    } //-- Byte getDatathrottle()

    /**
     * Get the type of loaded data.
     * 
     * @return Byte
     */
    public Byte getDatatype()
    {
        return this.datatype;
    } //-- Byte getDatatype()

    /**
     * Get disables item.
     * 
     * @return Byte
     */
    public Byte getDisabled()
    {
        return this.disabled;
    } //-- Byte getDisabled()

    /**
     * Get enables or disables drag-and-drop.
     * 
     * @return Byte
     */
    public Byte getDrag()
    {
        return this.drag;
    } //-- Byte getDrag()

    /**
     * Get enables autoscroll of component during drag-n-drop.
     * 
     * @return Byte
     */
    public Byte getDragscroll()
    {
        return this.dragscroll;
    } //-- Byte getDragscroll()

    /**
     * Get allows defining custom 'move' logic for the component.
     * 
     * @return Byte
     */
    public Byte getExternalData()
    {
        return this.externalData;
    } //-- Byte getExternalData()

    /**
     * Get sets the view gravity (1 by default).
     * 
     * @return Byte
     */
    public Byte getGravity()
    {
        return this.gravity;
    } //-- Byte getGravity()

    /**
     * Get sets the height of the component.
     * 
     * @return Byte
     */
    public Byte getHeight()
    {
        return this.height;
    } //-- Byte getHeight()

    /**
     * Get defines whether the view will be hidden initially.
     * 
     * @return Byte
     */
    public Byte getHidden()
    {
        return this.hidden;
    } //-- Byte getHidden()

    /**
     * Get the component ID.
     * 
     * @return Byte
     */
    public Byte getId()
    {
        return this.id;
    } //-- Byte getId()

    /**
     * Get defines x or y orientation of layout.
     * 
     * @return Byte
     */
    public Byte getLayout()
    {
        return this.layout;
    } //-- Byte getLayout()

    /**
     * Get sets the maximum height for the view.
     * 
     * @return Byte
     */
    public Byte getMaxHeight()
    {
        return this.maxHeight;
    } //-- Byte getMaxHeight()

    /**
     * Get sets the maximum width for the view.
     * 
     * @return Byte
     */
    public Byte getMaxWidth()
    {
        return this.maxWidth;
    } //-- Byte getMaxWidth()

    /**
     * Get sets the minimal height for the view.
     * 
     * @return Byte
     */
    public Byte getMinHeight()
    {
        return this.minHeight;
    } //-- Byte getMinHeight()

    /**
     * Get sets the minimal width for the view.
     * 
     * @return Byte
     */
    public Byte getMinWidth()
    {
        return this.minWidth;
    } //-- Byte getMinWidth()

    /**
     * Get the delay between a real mouse action and invoking the
     * related events.
     * 
     * @return Byte
     */
    public Byte getMouseEventDelay()
    {
        return this.mouseEventDelay;
    } //-- Byte getMouseEventDelay()

    /**
     * Get activates the selection keyboard navigation.
     * 
     * @return Byte
     */
    public Byte getNavigation()
    {
        return this.navigation;
    } //-- Byte getNavigation()

    /**
     * Get allows attaching custom handlers to inner events of the
     * component.
     * 
     * @return Byte
     */
    public Byte getOn()
    {
        return this.on;
    } //-- Byte getOn()

    /**
     * Get attaches a click behavior for component items with the
     * specified CSS class.
     * 
     * @return Byte
     */
    public Byte getOnClick()
    {
        return this.onClick;
    } //-- Byte getOnClick()

    /**
     * Get a property used to define custom context-click (right
     * click) handlers for elements in the DataTable cells.
     * 
     * @return Byte
     */
    public Byte getOnContext()
    {
        return this.onContext;
    } //-- Byte getOnContext()

    /**
     * Get attaches a dblclick behavior for component items with
     * the specified CSS class.
     * 
     * @return Byte
     */
    public Byte getOnDblClick()
    {
        return this.onDblClick;
    } //-- Byte getOnDblClick()

    /**
     * Get attaches a dblclick behavior for component items with
     * the specified CSS class.
     * 
     * @return Byte
     */
    public Byte getOnMouseMove()
    {
        return this.onMouseMove;
    } //-- Byte getOnMouseMove()

    /**
     * Get defines paging configuration ( creates a 'ui.pager'
     * object).
     * 
     * @return Byte
     */
    public Byte getPager()
    {
        return this.pager;
    } //-- Byte getPager()

    /**
     * Get a handler that is called just after the page has been
     * completely parsed.
     * 
     * @return Byte
     */
    public Byte getReady()
    {
        return this.ready;
    } //-- Byte getReady()

    /**
     * Get defines how to treat items in case of reloading.
     * 
     * @return Byte
     */
    public Byte getRemoveMissed()
    {
        return this.removeMissed;
    } //-- Byte getRemoveMissed()

    /**
     * Get set of validation rules for the component.
     * 
     * @return Byte
     */
    public Byte getRules()
    {
        return this.rules;
    } //-- Byte getRules()

    /**
     * Get defines urls for datasaving.
     * 
     * @return Byte
     */
    public Byte getSave()
    {
        return this.save;
    } //-- Byte getSave()

    /**
     * Get defines schemes for data processing.
     * 
     * @return Byte
     */
    public Byte getScheme()
    {
        return this.scheme;
    } //-- Byte getScheme()

    /**
     * Get enables/disables the scroll bar.
     * 
     * @return Byte
     */
    public Byte getScroll()
    {
        return this.scroll;
    } //-- Byte getScroll()

    /**
     * Get the time during which the component is scrolled to the
     * specified position (in milliseconds).
     * 
     * @return Byte
     */
    public Byte getScrollSpeed()
    {
        return this.scrollSpeed;
    } //-- Byte getScrollSpeed()

    /**
     * Get enables/disables item selection or multiselection in
     * grouplist.
     * 
     * @return Byte
     */
    public Byte getSelect()
    {
        return this.select;
    } //-- Byte getSelect()

    /**
     * Get the component template.
     * 
     * @return Byte
     */
    public Byte getTemplate()
    {
        return this.template;
    } //-- Byte getTemplate()

    /**
     * Get an html template that defines data that will be
     * presented in group header in the expanded state.
     * 
     * @return Byte
     */
    public Byte getTemplateBack()
    {
        return this.templateBack;
    } //-- Byte getTemplateBack()

    /**
     * Get sets the template according to which data will be copied
     * to the clipboard.
     * 
     * @return Byte
     */
    public Byte getTemplateCopy()
    {
        return this.templateCopy;
    } //-- Byte getTemplateCopy()

    /**
     * Get an html template that defines data that will be
     * presented in group header in the collapsed state.
     * 
     * @return Byte
     */
    public Byte getTemplateGroup()
    {
        return this.templateGroup;
    } //-- Byte getTemplateGroup()

    /**
     * Get an html template that defines data that will be
     * presented in grouplist.
     * 
     * @return Byte
     */
    public Byte getTemplateItem()
    {
        return this.templateItem;
    } //-- Byte getTemplateItem()

    /**
     * Get sets a popup message appearing on pointing a mouse
     * cursor over the dedicated item.
     * 
     * @return Byte
     */
    public Byte getTooltip()
    {
        return this.tooltip;
    } //-- Byte getTooltip()

    /**
     * Get object that specifies items presentation.
     * 
     * @return Byte
     */
    public Byte getType()
    {
        return this.type;
    } //-- Byte getType()

    /**
     * Get the url of a data feed which will be loaded after
     * component initialization.
     * 
     * @return Byte
     */
    public Byte getUrl()
    {
        return this.url;
    } //-- Byte getUrl()

    /**
     * Get sets the width of the component.
     * 
     * @return Byte
     */
    public Byte getWidth()
    {
        return this.width;
    } //-- Byte getWidth()

    /**
     * Get defines width of view in items.
     * 
     * @return Byte
     */
    public Byte getXCount()
    {
        return this.xCount;
    } //-- Byte getXCount()

    /**
     * Get defines height of view in items.
     * 
     * @return Byte
     */
    public Byte getYCount()
    {
        return this.yCount;
    } //-- Byte getYCount()

    /**
     * Set defines or disables view change animation.
     * 
     * @param animate
     */
    public void setAnimate( Byte animate )
    {
        this.animate = animate;
    } //-- void setAnimate( Byte )

    /**
     * Set height of view will be adjusted to show all items.
     * 
     * @param autoheight
     */
    public void setAutoheight( Byte autoheight )
    {
        this.autoheight = autoheight;
    } //-- void setAutoheight( Byte )

    /**
     * Set width of view will be adjusted to show all items.
     * 
     * @param autowidth
     */
    public void setAutowidth( Byte autowidth )
    {
        this.autowidth = autowidth;
    } //-- void setAutowidth( Byte )

    /**
     * Set used to hide the component borders.
     * 
     * @param borderless
     */
    public void setBorderless( Byte borderless )
    {
        this.borderless = borderless;
    } //-- void setBorderless( Byte )

    /**
     * Set sets an action happening on a button click.
     * 
     * @param click
     */
    public void setClick( Byte click )
    {
        this.click = click;
    } //-- void setClick( Byte )

    /**
     * Set enables/disables clipboard support.
     * 
     * @param clipboard
     */
    public void setClipboard( Byte clipboard )
    {
        this.clipboard = clipboard;
    } //-- void setClipboard( Byte )

    /**
     * Set an html container (or its id) where the component needs
     * initializing.
     * 
     * @param container
     */
    public void setContainer( Byte container )
    {
        this.container = container;
    } //-- void setContainer( Byte )

    /**
     * Set the name of a css class that will be applied to the view
     * container.
     * 
     * @param css
     */
    public void setCss( Byte css )
    {
        this.css = css;
    } //-- void setCss( Byte )

    /**
     * Set an inline dataset that data to the component will be
     * load from.
     * 
     * @param data
     */
    public void setData( Byte data )
    {
        this.data = data;
    } //-- void setData( Byte )

    /**
     * Set the url to the data source that the component will use
     * to reload data from.
     * 
     * @param dataFeed
     */
    public void setDataFeed( Byte dataFeed )
    {
        this.dataFeed = dataFeed;
    } //-- void setDataFeed( Byte )

    /**
     * Set sets the polling interval (the time period between the
     * completion of a network request and the next request for
     * data).
     * 
     * @param datathrottle
     */
    public void setDatathrottle( Byte datathrottle )
    {
        this.datathrottle = datathrottle;
    } //-- void setDatathrottle( Byte )

    /**
     * Set the type of loaded data.
     * 
     * @param datatype
     */
    public void setDatatype( Byte datatype )
    {
        this.datatype = datatype;
    } //-- void setDatatype( Byte )

    /**
     * Set disables item.
     * 
     * @param disabled
     */
    public void setDisabled( Byte disabled )
    {
        this.disabled = disabled;
    } //-- void setDisabled( Byte )

    /**
     * Set enables or disables drag-and-drop.
     * 
     * @param drag
     */
    public void setDrag( Byte drag )
    {
        this.drag = drag;
    } //-- void setDrag( Byte )

    /**
     * Set enables autoscroll of component during drag-n-drop.
     * 
     * @param dragscroll
     */
    public void setDragscroll( Byte dragscroll )
    {
        this.dragscroll = dragscroll;
    } //-- void setDragscroll( Byte )

    /**
     * Set allows defining custom 'move' logic for the component.
     * 
     * @param externalData
     */
    public void setExternalData( Byte externalData )
    {
        this.externalData = externalData;
    } //-- void setExternalData( Byte )

    /**
     * Set sets the view gravity (1 by default).
     * 
     * @param gravity
     */
    public void setGravity( Byte gravity )
    {
        this.gravity = gravity;
    } //-- void setGravity( Byte )

    /**
     * Set sets the height of the component.
     * 
     * @param height
     */
    public void setHeight( Byte height )
    {
        this.height = height;
    } //-- void setHeight( Byte )

    /**
     * Set defines whether the view will be hidden initially.
     * 
     * @param hidden
     */
    public void setHidden( Byte hidden )
    {
        this.hidden = hidden;
    } //-- void setHidden( Byte )

    /**
     * Set the component ID.
     * 
     * @param id
     */
    public void setId( Byte id )
    {
        this.id = id;
    } //-- void setId( Byte )

    /**
     * Set defines x or y orientation of layout.
     * 
     * @param layout
     */
    public void setLayout( Byte layout )
    {
        this.layout = layout;
    } //-- void setLayout( Byte )

    /**
     * Set sets the maximum height for the view.
     * 
     * @param maxHeight
     */
    public void setMaxHeight( Byte maxHeight )
    {
        this.maxHeight = maxHeight;
    } //-- void setMaxHeight( Byte )

    /**
     * Set sets the maximum width for the view.
     * 
     * @param maxWidth
     */
    public void setMaxWidth( Byte maxWidth )
    {
        this.maxWidth = maxWidth;
    } //-- void setMaxWidth( Byte )

    /**
     * Set sets the minimal height for the view.
     * 
     * @param minHeight
     */
    public void setMinHeight( Byte minHeight )
    {
        this.minHeight = minHeight;
    } //-- void setMinHeight( Byte )

    /**
     * Set sets the minimal width for the view.
     * 
     * @param minWidth
     */
    public void setMinWidth( Byte minWidth )
    {
        this.minWidth = minWidth;
    } //-- void setMinWidth( Byte )

    /**
     * Set the delay between a real mouse action and invoking the
     * related events.
     * 
     * @param mouseEventDelay
     */
    public void setMouseEventDelay( Byte mouseEventDelay )
    {
        this.mouseEventDelay = mouseEventDelay;
    } //-- void setMouseEventDelay( Byte )

    /**
     * Set activates the selection keyboard navigation.
     * 
     * @param navigation
     */
    public void setNavigation( Byte navigation )
    {
        this.navigation = navigation;
    } //-- void setNavigation( Byte )

    /**
     * Set allows attaching custom handlers to inner events of the
     * component.
     * 
     * @param on
     */
    public void setOn( Byte on )
    {
        this.on = on;
    } //-- void setOn( Byte )

    /**
     * Set attaches a click behavior for component items with the
     * specified CSS class.
     * 
     * @param onClick
     */
    public void setOnClick( Byte onClick )
    {
        this.onClick = onClick;
    } //-- void setOnClick( Byte )

    /**
     * Set a property used to define custom context-click (right
     * click) handlers for elements in the DataTable cells.
     * 
     * @param onContext
     */
    public void setOnContext( Byte onContext )
    {
        this.onContext = onContext;
    } //-- void setOnContext( Byte )

    /**
     * Set attaches a dblclick behavior for component items with
     * the specified CSS class.
     * 
     * @param onDblClick
     */
    public void setOnDblClick( Byte onDblClick )
    {
        this.onDblClick = onDblClick;
    } //-- void setOnDblClick( Byte )

    /**
     * Set attaches a dblclick behavior for component items with
     * the specified CSS class.
     * 
     * @param onMouseMove
     */
    public void setOnMouseMove( Byte onMouseMove )
    {
        this.onMouseMove = onMouseMove;
    } //-- void setOnMouseMove( Byte )

    /**
     * Set defines paging configuration ( creates a 'ui.pager'
     * object).
     * 
     * @param pager
     */
    public void setPager( Byte pager )
    {
        this.pager = pager;
    } //-- void setPager( Byte )

    /**
     * Set a handler that is called just after the page has been
     * completely parsed.
     * 
     * @param ready
     */
    public void setReady( Byte ready )
    {
        this.ready = ready;
    } //-- void setReady( Byte )

    /**
     * Set defines how to treat items in case of reloading.
     * 
     * @param removeMissed
     */
    public void setRemoveMissed( Byte removeMissed )
    {
        this.removeMissed = removeMissed;
    } //-- void setRemoveMissed( Byte )

    /**
     * Set set of validation rules for the component.
     * 
     * @param rules
     */
    public void setRules( Byte rules )
    {
        this.rules = rules;
    } //-- void setRules( Byte )

    /**
     * Set defines urls for datasaving.
     * 
     * @param save
     */
    public void setSave( Byte save )
    {
        this.save = save;
    } //-- void setSave( Byte )

    /**
     * Set defines schemes for data processing.
     * 
     * @param scheme
     */
    public void setScheme( Byte scheme )
    {
        this.scheme = scheme;
    } //-- void setScheme( Byte )

    /**
     * Set enables/disables the scroll bar.
     * 
     * @param scroll
     */
    public void setScroll( Byte scroll )
    {
        this.scroll = scroll;
    } //-- void setScroll( Byte )

    /**
     * Set the time during which the component is scrolled to the
     * specified position (in milliseconds).
     * 
     * @param scrollSpeed
     */
    public void setScrollSpeed( Byte scrollSpeed )
    {
        this.scrollSpeed = scrollSpeed;
    } //-- void setScrollSpeed( Byte )

    /**
     * Set enables/disables item selection or multiselection in
     * grouplist.
     * 
     * @param select
     */
    public void setSelect( Byte select )
    {
        this.select = select;
    } //-- void setSelect( Byte )

    /**
     * Set the component template.
     * 
     * @param template
     */
    public void setTemplate( Byte template )
    {
        this.template = template;
    } //-- void setTemplate( Byte )

    /**
     * Set an html template that defines data that will be
     * presented in group header in the expanded state.
     * 
     * @param templateBack
     */
    public void setTemplateBack( Byte templateBack )
    {
        this.templateBack = templateBack;
    } //-- void setTemplateBack( Byte )

    /**
     * Set sets the template according to which data will be copied
     * to the clipboard.
     * 
     * @param templateCopy
     */
    public void setTemplateCopy( Byte templateCopy )
    {
        this.templateCopy = templateCopy;
    } //-- void setTemplateCopy( Byte )

    /**
     * Set an html template that defines data that will be
     * presented in group header in the collapsed state.
     * 
     * @param templateGroup
     */
    public void setTemplateGroup( Byte templateGroup )
    {
        this.templateGroup = templateGroup;
    } //-- void setTemplateGroup( Byte )

    /**
     * Set an html template that defines data that will be
     * presented in grouplist.
     * 
     * @param templateItem
     */
    public void setTemplateItem( Byte templateItem )
    {
        this.templateItem = templateItem;
    } //-- void setTemplateItem( Byte )

    /**
     * Set sets a popup message appearing on pointing a mouse
     * cursor over the dedicated item.
     * 
     * @param tooltip
     */
    public void setTooltip( Byte tooltip )
    {
        this.tooltip = tooltip;
    } //-- void setTooltip( Byte )

    /**
     * Set object that specifies items presentation.
     * 
     * @param type
     */
    public void setType( Byte type )
    {
        this.type = type;
    } //-- void setType( Byte )

    /**
     * Set the url of a data feed which will be loaded after
     * component initialization.
     * 
     * @param url
     */
    public void setUrl( Byte url )
    {
        this.url = url;
    } //-- void setUrl( Byte )

    /**
     * Set sets the width of the component.
     * 
     * @param width
     */
    public void setWidth( Byte width )
    {
        this.width = width;
    } //-- void setWidth( Byte )

    /**
     * Set defines width of view in items.
     * 
     * @param xCount
     */
    public void setXCount( Byte xCount )
    {
        this.xCount = xCount;
    } //-- void setXCount( Byte )

    /**
     * Set defines height of view in items.
     * 
     * @param yCount
     */
    public void setYCount( Byte yCount )
    {
        this.yCount = yCount;
    } //-- void setYCount( Byte )

    /**
     * Adds an item to the store
     */
    public Byte add() {
        return null;
    }
    /**
     * Applied CSS class to a component item
     */
    public void addCss() {
        return;
    }
    /**
     * Adjusts the component to the size of the parent HTML container
     */
    public void adjust() {
        return;
    }
    /**
     * Attaches the handler to an inner event of the component (allows behaviour customizations)
     */
    public Byte attachEvent() {
        return null;
    }
    /**
     * Binds components
     */
    public void bind() {
        return;
    }
    /**
     * Temporarily blocks triggering of ALL events of the calling object
     */
    public void blockEvent() {
        return;
    }
    /**
     * Calls an inner event
     */
    public Boolean callEvent() {
        return null;
    }
    /**
     * Removes all items from the component
     */
    public void clearAll() {
        return;
    }
    /**
     * Removes css class from all items
     */
    public void clearCss() {
        return;
    }
    /**
     * Removes all validation marks from the component
     */
    public void clearValidation() {
        return;
    }
    /**
     * Copies an item to the same or another object
     */
    public void copy() {
        return;
    }
    /**
     * Returns the count of items in the table
     */
    public Integer count() {
        return null;
    }
    /**
     * Redefines the 'type' property
     */
    public void customize() {
        return;
    }
    /**
     * Redefines a single configuration property (or a hash of properties)
     */
    public void define() {
        return;
    }
    /**
     * Destructs the calling object
     */
    public void destructor() {
        return;
    }
    /**
     * Detaches a handler from an event (which was attached before by the attachEvent method)
     */
    public void detachEvent() {
        return;
    }
    /**
     * Disables the calling view (makes it dimmed and unclickable)
     */
    public void disable() {
        return;
    }
    /**
     * Enables the calling view that was disabled by the 'disable' method
     */
    public void enable() {
        return;
    }
    /**
     * Checks whether an item with the specified id exists
     */
    public Boolean exists() {
        return null;
    }
    /**
     * Filters the component
     */
    public void filter() {
        return;
    }
    /**
     * Returns child views of the calling component
     */
    public Byte getChildViews() {
        return null;
    }
    /**
     * Returns the ID of the first item
     */
    public Byte getFirstId() {
        return null;
    }
    /**
     * Returns master form for the input
     */
    public Byte getFormView() {
        return null;
    }
    /**
     * Returns the id of the item with the specified index
     */
    public Byte getIdByIndex() {
        return null;
    }
    /**
     * Returns the index of the item with the specified id
     */
    public Integer getIndexById() {
        return null;
    }
    /**
     * Gets the object of the data item with the specified id
     */
    public Byte getItem() {
        return null;
    }
    /**
     * Returns html element of the item
     */
    public void getItemNode() {
        return;
    }
    /**
     * Returns the id of the last item
     */
    public Byte getLastId() {
        return null;
    }
    /**
     * Returns the ID of an item which is positioned the specified step after the specified item
     */
    public Byte getNextId() {
        return null;
    }
    /**
     * Returns the main HTML container for the calling object
     */
    public Byte getNode() {
        return null;
    }
    /**
     * Gets IDs of items taking part in the current group opening
     */
    public Byte getOpenState() {
        return null;
    }
    /**
     * Returns the currently visible page in case of paged view
     */
    public Integer getPage() {
        return null;
    }
    /**
     * Returns the parent view of the component
     */
    public Byte getParentView() {
        return null;
    }
    /**
     * Returns the ID of an item which is positioned the specified step before the specified item
     */
    public Byte getPrevId() {
        return null;
    }
    /**
     * Returns the scroll position
     */
    public Byte getScrollState() {
        return null;
    }
    /**
     * Returns the id(s) of the selected item(s)
     */
    public Byte getSelectedId() {
        return null;
    }
    /**
     * Returns selected object
     */
    public Byte getSelectedItem() {
        return null;
    }
    /**
     * Returns top parent view
     */
    public Byte getTopParentView() {
        return null;
    }
    /**
     * Returns the number of items that can be seen with the current view height
     */
    public Integer getVisibleCount() {
        return null;
    }
    /**
     * Groups data by the specified data property
     */
    public void group() {
        return;
    }
    /**
     * Checks if item has specific css class
     */
    public Boolean hasCss() {
        return null;
    }
    /**
     * Checks whether the component has the specified event
     */
    public Boolean hasEvent() {
        return null;
    }
    /**
     * Hides the view
     */
    public void hide() {
        return;
    }
    /**
     * Checks whether the view is enabled
     */
    public Boolean isEnabled() {
        return null;
    }
    /**
     * Checks whether the specified item is selected or not
     */
    public Boolean isSelected() {
        return null;
    }
    /**
     * Checks whether the view is visible
     */
    public Boolean isVisible() {
        return null;
    }
    /**
     * Loads data from an external data source
     */
    public Byte load() {
        return null;
    }
    /**
     * Sends a request to load the specified number of records to the end or to the specified position
     */
    public void loadNext() {
        return;
    }
    /**
     * Gets the id of an item from the specified HTML event
     */
    public Byte locate() {
        return null;
    }
    /**
     * Routes events from one object to another
     */
    public void mapEvent() {
        return;
    }
    /**
     * Moves the specified item to the new position
     */
    public String move() {
        return null;
    }
    /**
     * Moves the specified item to the last position
     */
    public void moveBottom() {
        return;
    }
    /**
     * Increases the item index and moves the item to the new position
     */
    public void moveDown() {
        return;
    }
    /**
     * Moves selection in the specified direction
     */
    public void moveSelection() {
        return;
    }
    /**
     * Moves the specified item to the first position
     */
    public void moveTop() {
        return;
    }
    /**
     * Decreases the item index and moves the item to the new position
     */
    public void moveUp() {
        return;
    }
    /**
     * Loads data to the component from an inline data source
     */
    public void parse() {
        return;
    }
    /**
     * Repaints the whole view or a certain item
     */
    public void refresh() {
        return;
    }
    /**
     * Removes the specified item from datastore
     */
    public void remove() {
        return;
    }
    /**
     * Removes CSS class from a component item
     */
    public void removeCss() {
        return;
    }
    /**
     * Renders the specified item or the whole component
     */
    public void render() {
        return;
    }
    /**
     * Adjusts the view to a new size
     */
    public void resize() {
        return;
    }
    /**
     * Scrolls the data container to a certain position
     */
    public void scrollTo() {
        return;
    }
    /**
     * Selects the specified item(s)
     */
    public void select() {
        return;
    }
    /**
     * Selects all items or the specified range
     */
    public void selectAll() {
        return;
    }
    /**
     * Serializes data to a json object
     */
    public Byte serialize() {
        return null;
    }
    /**
     * Makes the specified page visible (assuming that the pager was defined )
     */
    public void setPage() {
        return;
    }
    /**
     * Makes the component visible
     */
    public void show() {
        return;
    }
    /**
     * Scrolls the component to make the specified item visible
     */
    public void showItem() {
        return;
    }
    /**
     * Sorts datastore
     */
    public void sort() {
        return;
    }
    /**
     * Allows you to sync two copy of data (all or just a part of it) from one DataCollection to another
     */
    public void sync() {
        return;
    }
    /**
     * Breaks "bind" link
     */
    public void unbind() {
        return;
    }
    /**
     * Cancels blocking events that was enabled by the 'blockEvent' command
     */
    public void unblockEvent() {
        return;
    }
    /**
     * Ungroups data
     */
    public void ungroup() {
        return;
    }
    /**
     * Removes selection from the specified item
     */
    public void unselect() {
        return;
    }
    /**
     * Removes selection from all items
     */
    public void unselectAll() {
        return;
    }
    /**
     * Sets properties of the data item
     */
    public void updateItem() {
        return;
    }
    /**
     * Validates one record or all dataset against validation rules
     */
    public Boolean validate() {
        return null;
    }
}
